/*
===========================================================================

  Copyright (c) 2025 LandSandBoat Dev Teams

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see http://www.gnu.org/licenses/

===========================================================================
*/

#include <test/test_application.h>

#include <common/lua.h>
#include <common/tracy.h>
#include <map/utils/charutils.h>

#include <cstdlib>
#include <iostream>
#include <memory>

auto runEarthTimeSelfTests() -> bool;
auto runIPPSelfTests() -> bool;
auto runBitpackSelfTests() -> bool;
auto runBlowfishSelfTests() -> bool;
auto runBlacklistPersistenceRuntimeSelfTests() -> bool;
auto runDataEnumTraitsSelfTests() -> bool;
auto runStringCodecSelfTests() -> bool;
auto runSJISCodecSelfTests() -> bool;
auto runSpatialOrientationSelfTests() -> bool;
auto runNumericUtilsSelfTests() -> bool;
auto runStringUtilsSelfTests() -> bool;
auto runConsoleServiceInputSelfTests() -> bool;
auto runLookParserSelfTests() -> bool;
auto runHashUtilsSelfTests() -> bool;
auto runRngEnginesSelfTests() -> bool;
auto runXiBitsetSelfTests() -> bool;
auto runCircularBufferSelfTests() -> bool;
auto runCraftStateSelfTests() -> bool;
auto runTimerHelpersSelfTests() -> bool;
auto runSynchronizedSelfTests() -> bool;
auto runTypedFlagsSelfTests() -> bool;
auto runMaybeOptionalSelfTests() -> bool;
auto runMMOConfigTypesSelfTests() -> bool;
auto runMMOEminenceSelfTests() -> bool;
auto runMMOKeyItemsSelfTests() -> bool;
auto runMMOProgressLogSelfTests() -> bool;
auto runMMOSearchBazaarSelfTests() -> bool;
auto runMMOStatsSkillsSelfTests() -> bool;
auto runUUIDGenerationSelfTests() -> bool;
auto runZlibCompressedSizeSelfTests() -> bool;
auto runZlibCodecSelfTests() -> bool;
auto runFileUtilsSelfTests() -> bool;
auto runRateLimitUtilsSelfTests() -> bool;
auto runEventInfoSelfTests() -> bool;
auto runLatentEffectSelfTests() -> bool;
auto runArgumentsParserSelfTests() -> bool;
auto runAuctionTransactionRuntimeSelfTests() -> bool;
auto runDeliveryBoxTransactionRuntimeSelfTests() -> bool;
auto runActionModelSelfTests() -> bool;
auto runActionQueueSelfTests() -> bool;
auto runInstanceLifecycleSelfTests() -> bool;
auto runInstanceUtilsRuntimeSelfTests() -> bool;
auto runBaseEntityModelSelfTests() -> bool;
auto runVersionInfoSelfTests() -> bool;
auto runSingletonHelperSelfTests() -> bool;
auto runInventorySyncStateSelfTests() -> bool;
auto runItemAccessSelfTests() -> bool;
auto runItemContainerSelfTests() -> bool;
auto runItemCurrencySelfTests() -> bool;
auto runItemEquipmentSelfTests() -> bool;
auto runItemExdataSelfTests() -> bool;
auto runItemFishSelfTests() -> bool;
auto runItemFlowerpotSelfTests() -> bool;
auto runItemFurnishingSelfTests() -> bool;
auto runItemGeneralSelfTests() -> bool;
auto runItemLinkshellSelfTests() -> bool;
auto runItemPuppetSelfTests() -> bool;
auto runItemShopSelfTests() -> bool;
auto runItemTransactionSelfTests() -> bool;
auto runItemUsableSelfTests() -> bool;
auto runItemWeaponSelfTests() -> bool;
auto runGradesSelfTests() -> bool;
auto runGuildPatternRuntimeSelfTests() -> bool;
auto runBlueMagicSetRuntime1233SelfTests() -> bool;
auto runTradeContainerSelfTests() -> bool;
auto runUniversalContainerSelfTests() -> bool;
auto runRecastContainerSelfTests() -> bool;
auto runTraitSelfTests() -> bool;
auto runJobPointsSelfTests() -> bool;
auto runEnmityContainerSelfTests() -> bool;
auto runModifierSelfTests() -> bool;
auto runMazeSelfTests() -> bool;
auto runNotorietyContainerSelfTests() -> bool;
auto runSpawnSlotSelfTests() -> bool;
auto runStatusEffectModelSelfTests() -> bool;
auto runStatusEffectContainerSelfTests() -> bool;
auto runStatusEffectDataSelfTests() -> bool;
auto runTimeTriggerSelfTests() -> bool;
auto runTransportRuntimeSelfTests() -> bool;
auto runSpatialGridSelfTests() -> bool;
auto runXimeshMathSelfTests() -> bool;
auto runXimeshStructsSelfTests() -> bool;
auto runXimeshNullMeshSelfTests() -> bool;
auto runDatabaseQueryHelpersSelfTests() -> bool;
auto runLoggingUntrustedStringsSelfTests() -> bool;
auto runLoggingBacktraceBufferSelfTests() -> bool;
auto runLoginMalformedStringSelfTests() -> bool;
auto runLoginCertHelpersSelfTests() -> bool;
auto runLoginDisplayBitmasksSelfTests() -> bool;
auto runLoginErrorPacketSelfTests() -> bool;
auto runLoginOTPHelpersSelfTests() -> bool;
auto runSettingsNumberHelperSelfTests() -> bool;
auto runSettingsValueConversionsSelfTests() -> bool;
auto runSettingsLoaderSelfTests() -> bool;
auto runLOSCacheSelfTests() -> bool;
auto runLinkshellSelfTests() -> bool;
auto runMapStatisticsSelfTests() -> bool;
auto runLoginPacketHashSelfTests() -> bool;
auto runLoginJSONGetSelfTests() -> bool;
auto runLoginKeyPacketSelfTests() -> bool;
auto runLoginVersionLockSelfTests() -> bool;
auto runMapNetworkPacketBuildingSelfTests() -> bool;
auto runMapSessionBlowfishSelfTests() -> bool;
auto runMapSessionIndexSelfTests() -> bool;
auto runSQLiteQueryTranslationSelfTests() -> bool;
auto runMariaDBConnectionLossSelfTests() -> bool;
auto runMariaDBResultCellConversionsSelfTests() -> bool;
auto runMariaDBResultSetMetadataSelfTests() -> bool;
auto runResultSetTypedGettersSelfTests() -> bool;
auto runDatabaseBindingSelfTests() -> bool;
auto runActiveDatabaseDispatchSelfTests() -> bool;
auto runDatabaseConvenienceHelpersSelfTests() -> bool;
auto runCachingDatabaseSelfTests() -> bool;
auto runIPCChannelSelfTests() -> bool;
auto runZmqEndpointOpenedSelfTests() -> bool;
auto runFilewatcherQueueSelfTests() -> bool;
auto runGardenResultRuntimeSelfTests() -> bool;
auto runLoggingJsonRendererSelfTests() -> bool;
auto runLoggingContextStackSelfTests() -> bool;
auto runXirandHelpersSelfTests() -> bool;
auto runIPCMessageTypeSelfTests() -> bool;
auto runIPCChatPayloadSelfTests() -> bool;
auto runIPCDispatch1248SelfTests() -> bool;
auto runIPCSessionPayloadSelfTests() -> bool;
auto runIPCPartyPayloadSelfTests() -> bool;
auto runIPCLinkshellPayloadSelfTests() -> bool;
auto runIPCGMCallPayloadSelfTests() -> bool;
auto runGMCallAssembly1238SelfTests() -> bool;
auto runGMCallPendingResponse1239SelfTests() -> bool;
auto runGMCallPacketHandlers1242SelfTests() -> bool;
auto runGMCallPersistence1243SelfTests() -> bool;
auto runMapGMCallResponseNotification1241SelfTests() -> bool;
auto runMapAccountLogin1253SelfTests() -> bool;
auto runMapCharZone1254SelfTests() -> bool;
auto runMapCharVarUpdate1256SelfTests() -> bool;
auto runMapChatMessageTell1258SelfTests() -> bool;
auto runMapAssistChannelEvent1290SelfTests() -> bool;
auto runMapPlayerRelocation1291SelfTests() -> bool;
auto runMapEntityInformationRequest1292SelfTests() -> bool;
auto runMapStandardMessageDelivery1293SelfTests() -> bool;
auto runMapPlayerKickRefresh1294SelfTests() -> bool;
auto runMapPartyAllianceUpdates1295SelfTests() -> bool;
auto runMapLinkshellUpdates1296SelfTests() -> bool;
auto runMapGroupChatDelivery1297SelfTests() -> bool;
auto runMapZoneWideChatDelivery1298SelfTests() -> bool;
auto runMapChatMessageCustom1299SelfTests() -> bool;
auto runMapPartyInvite1300SelfTests() -> bool;
auto runMapKillSession1301SelfTests() -> bool;
auto runMapRegionalEventDispatch1302SelfTests() -> bool;
auto runMapPartyInviteResponse1303SelfTests() -> bool;
auto runMapLuaFunction1304SelfTests() -> bool;
auto runMapIPCDiagnostics1305SelfTests() -> bool;
auto runMapGMCallRequest1306SelfTests() -> bool;
auto runWorldChatMessageParty1259SelfTests() -> bool;
auto runWorldChatMessageAlliance1260SelfTests() -> bool;
auto runWorldChatMessageLinkshell1261SelfTests() -> bool;
auto runWorldChatMessageUnity1262SelfTests() -> bool;
auto runWorldChatMessageYell1263SelfTests() -> bool;
auto runWorldChatMessageAssist1264SelfTests() -> bool;
auto runWorldChatMessageServerMessage1265SelfTests() -> bool;
auto runWorldChatMessageCustom1266SelfTests() -> bool;
auto runWorldPartyInvite1267SelfTests() -> bool;
auto runWorldPartyInviteResponse1268SelfTests() -> bool;
auto runWorldPartyReload1269SelfTests() -> bool;
auto runWorldPartyDisband1270SelfTests() -> bool;
auto runWorldAllianceReload1271SelfTests() -> bool;
auto runWorldAllianceDissolve1272SelfTests() -> bool;
auto runWorldPlayerKick1273SelfTests() -> bool;
auto runWorldMessageStandard1274SelfTests() -> bool;
auto runWorldMessageSystem1275SelfTests() -> bool;
auto runWorldLinkshellRankChange1276SelfTests() -> bool;
auto runWorldLinkshellRemove1277SelfTests() -> bool;
auto runWorldLinkshellSetMessage1278SelfTests() -> bool;
auto runWorldLuaFunction1279SelfTests() -> bool;
auto runWorldKillSession1280SelfTests() -> bool;
auto runWorldConquestEvent1281SelfTests() -> bool;
auto runWorldBesiegedEvent1282SelfTests() -> bool;
auto runWorldCampaignEvent1283SelfTests() -> bool;
auto runWorldColonizationEvent1284SelfTests() -> bool;
auto runWorldEntityInformationRequest1285SelfTests() -> bool;
auto runWorldEntityInformationResponse1286SelfTests() -> bool;
auto runWorldSendPlayerToLocation1287SelfTests() -> bool;
auto runWorldAssistChannelEvent1288SelfTests() -> bool;
auto runWorldIPCDiagnostics1289SelfTests() -> bool;
auto runIPCRegionalPayloadSelfTests() -> bool;
auto runIPCStandardMessagePayloadSelfTests() -> bool;
auto runIPCMessageFramingSelfTests() -> bool;
auto runTracyHexHelperSelfTests() -> bool;
auto runTriggerAreaSelfTests() -> bool;
auto runTreasurePoolResolutionSelfTests() -> bool;
auto runWeatherContainerSelfTests() -> bool;
auto runMapEnumPrimitiveSelfTests() -> bool;
auto runMountStateRuntime1234SelfTests() -> bool;
auto runLoginErrorCodeSelfTests() -> bool;
auto runLoginAuthConstantSelfTests() -> bool;
auto runLoginAuthPassword1307SelfTests() -> bool;
auto runLoginAuthVersionError1308SelfTests() -> bool;
auto runLoginAuthAccountID1309SelfTests() -> bool;
auto runLoginAuthAccountCreate1310SelfTests() -> bool;
auto runLoginAuthChangePassword1311SelfTests() -> bool;
auto runLoginAuthTOTPURI1312SelfTests() -> bool;
auto runLoginAuthOTPRecovery1313SelfTests() -> bool;
auto runLoginAuthLoginAttemptOTP1314SelfTests() -> bool;
auto runLoginAuthSuccessReply1315SelfTests() -> bool;
auto runLoginCharacterName1316SelfTests() -> bool;
auto runLoginViewLobbyAck1317SelfTests() -> bool;
auto runLoginCharacterSelect1318SelfTests() -> bool;
auto runLoginCharacterDelete1319SelfTests() -> bool;
auto runLoginCharacterCreate1320SelfTests() -> bool;
auto runLoginViewAcquirePlayer1321SelfTests() -> bool;
auto runLoginSessionCleanup1322SelfTests() -> bool;
auto runLoginDataA11323SelfTests() -> bool;
auto runLoginDataA21324SelfTests() -> bool;
auto runLoginConnectCleanup1325SelfTests() -> bool;
auto runLoginConnectConsole1326SelfTests() -> bool;
auto runPartyCapacity1327SelfTests() -> bool;
auto runPartyMemberCount1328SelfTests() -> bool;
auto runAllianceCapacity1329SelfTests() -> bool;
auto runPartyLevelSync1330SelfTests() -> bool;
auto runLoginConnectApp1331SelfTests() -> bool;
auto runMapAppConfig1332SelfTests() -> bool;
auto runWorldAppConfig1333SelfTests() -> bool;
auto runPartySetSyncTarget1334SelfTests() -> bool;
auto runPartyPushPacket1335SelfTests() -> bool;
auto runPartyGroupEffects1336SelfTests() -> bool;
auto runMapGMConsole1337SelfTests() -> bool;
auto runMapEngineConfig1338SelfTests() -> bool;
auto runAllianceDissolve1339SelfTests() -> bool;
auto runPartyRemoveLeader1340SelfTests() -> bool;
auto runAllianceRemoveParty1341SelfTests() -> bool;
auto runMapMainExit1342SelfTests() -> bool;
auto runFixedMainExit1343SelfTests() -> bool;
auto runSearchMainExit1344SelfTests() -> bool;
auto runPartyDisband1345SelfTests() -> bool;
auto runAllianceAssignLeader1346SelfTests() -> bool;
auto runPartyAssignRole1347SelfTests() -> bool;
auto runPartyMemberLookup1348SelfTests() -> bool;
auto runPartyRemoveMember1349SelfTests() -> bool;
auto runPartyAddMember1350SelfTests() -> bool;
auto runPartyPushPopDel1351SelfTests() -> bool;
auto runPartyReload1352SelfTests() -> bool;
auto runPartyMemberFlags1353SelfTests() -> bool;
auto runLinkshellCapacity1354SelfTests() -> bool;
auto runLinkshellRegistry1355SelfTests() -> bool;
auto runUnityChatCapacity1356SelfTests() -> bool;
auto runGuildPointsMath1358SelfTests() -> bool;
auto runLatentConditionEval1359SelfTests() -> bool;
auto runLatentConditionEval1360SelfTests() -> bool;
auto runBattlefieldPolicy1361SelfTests() -> bool;
auto runSpawnCanSpawn1362SelfTests() -> bool;
auto runZonePolicy1363SelfTests() -> bool;
auto runStatusEffectCanGain1364SelfTests() -> bool;
auto runStatusEffectSelection1365SelfTests() -> bool;
auto runStatusEffectTick1366SelfTests() -> bool;
auto runTreasurePoolPolicy1367SelfTests() -> bool;
auto runStatusEffectPrevent1368SelfTests() -> bool;
auto runStatusEffectParams1369SelfTests() -> bool;
auto runRecastCharge1370SelfTests() -> bool;
auto runStatusEffectAddRemove1371SelfTests() -> bool;
auto runStatusEffectDelete1372SelfTests() -> bool;
auto runStatusEffectSave1373SelfTests() -> bool;
auto runAttackRoundMultihit1374SelfTests() -> bool;
auto runAttackRoundFollowUp1375SelfTests() -> bool;
auto runAttackChecks1376SelfTests() -> bool;
auto runAttackDamage1377SelfTests() -> bool;
auto runAttackAssembly1378SelfTests() -> bool;
auto runAttackHitRate1379SelfTests() -> bool;
auto runAttackutilsMultiplier1380SelfTests() -> bool;
auto runRangeState1381SelfTests() -> bool;
auto runMagicState1382SelfTests() -> bool;
auto runAbilityState1383SelfTests() -> bool;
auto runWeaponSkillState1384SelfTests() -> bool;
auto runMobSkillState1385SelfTests() -> bool;
auto runPetSkillState1386SelfTests() -> bool;
auto runAttackState1387SelfTests() -> bool;
auto runCanAttack1388SelfTests() -> bool;
auto runRangedHitCount1389SelfTests() -> bool;
auto runRangedAmmo1390SelfTests() -> bool;
auto runCamouflageRetain1391SelfTests() -> bool;
auto runRangedAdditionalEffect1392SelfTests() -> bool;
auto runRangedOutcome1393SelfTests() -> bool;
auto runRangedActorFinalize1394SelfTests() -> bool;
auto runDisengage1395SelfTests() -> bool;
auto runAttackEntry1396SelfTests() -> bool;
auto runAttackSwingGate1397SelfTests() -> bool;
auto runAttackHitPath1398SelfTests() -> bool;
auto runAttackPostSwing1399SelfTests() -> bool;
auto runZanshin1400SelfTests() -> bool;
auto runDakenSangeAmmo1401SelfTests() -> bool;
auto runAttackLoop1402SelfTests() -> bool;
auto runEngage1403SelfTests() -> bool;
auto runDespawnFinalize1404SelfTests() -> bool;
auto runPostTickDeath1405SelfTests() -> bool;
auto runHitInterrupt1406SelfTests() -> bool;
auto runBattleTime1407SelfTests() -> bool;
auto runBattleIdentity1408SelfTests() -> bool;
auto runEnmityPresence1409SelfTests() -> bool;
auto runDeathFinalize1410SelfTests() -> bool;
auto runBattleSpawn1411SelfTests() -> bool;
auto runMobDeath1412SelfTests() -> bool;
auto runMobDeathReward1413SelfTests() -> bool;
auto runPetDeath1414SelfTests() -> bool;
auto runTrustDeath1415SelfTests() -> bool;
auto runAutomatonDeath1416SelfTests() -> bool;
auto runPetSpawn1417SelfTests() -> bool;
auto runTrustSpawn1418SelfTests() -> bool;
auto runPetZoningRestore1419SelfTests() -> bool;
auto runPetPostTick1420SelfTests() -> bool;
auto runAutomatonPostTick1421SelfTests() -> bool;
auto runPetFadeOut1422SelfTests() -> bool;
auto runTrustFadeOut1423SelfTests() -> bool;
auto runTrustPostTick1424SelfTests() -> bool;
auto runTrustDespawn1425SelfTests() -> bool;
auto runTrustCastFinished1426SelfTests() -> bool;
auto runTrustValidTarget1427SelfTests() -> bool;
auto runPetValidTarget1428SelfTests() -> bool;
auto runPetJugTimer1429SelfTests() -> bool;
auto runPetCanAttack1430SelfTests() -> bool;
auto runPetAbility1431SelfTests() -> bool;
auto runPetAbilityResult1432SelfTests() -> bool;
auto runPetConstruction1433SelfTests() -> bool;
auto runCharPetZoning1434SelfTests() -> bool;
auto runCharAutomaton1435SelfTests() -> bool;
auto runCharStorage1436SelfTests() -> bool;
auto runCharPlaytime1437SelfTests() -> bool;
auto runCharBazaar1438SelfTests() -> bool;
auto runCharName1439SelfTests() -> bool;
auto runCharResource1440SelfTests() -> bool;
auto runCharEquipment1441SelfTests() -> bool;
auto runCharTrustRoster1442SelfTests() -> bool;
auto runCharPersistence1443SelfTests() -> bool;
auto runCharTick1444SelfTests() -> bool;
auto runCharPostTickRefresh1445SelfTests() -> bool;
auto runCharPostTickUpdate1446SelfTests() -> bool;
auto runCharEquipFlush1447SelfTests() -> bool;
auto runCharValidTarget1448SelfTests() -> bool;
auto runCharCombatTransition1449SelfTests() -> bool;
auto runCharActionBoundary1450SelfTests() -> bool;
auto runCharErrorDelivery1451SelfTests() -> bool;
auto runCharDeathHomepoint1452SelfTests() -> bool;
auto runCharTriggerArea1453SelfTests() -> bool;
auto runCharEventLock1454SelfTests() -> bool;
auto runCharEventQueue1455SelfTests() -> bool;
auto runCharEventSkip1456SelfTests() -> bool;
auto runCharEventIdle1457SelfTests() -> bool;
auto runCharEventActivation1458SelfTests() -> bool;
auto runCharEventPacket1459SelfTests() -> bool;
auto runCharHighestJob1460SelfTests() -> bool;
auto runCharMoghancementState1461SelfTests() -> bool;
auto runCharMoghancementFurniture1462SelfTests() -> bool;
auto runCharMoghancementUpdate1463SelfTests() -> bool;
auto runCharMoghancementCraft1464SelfTests() -> bool;
auto runCharMoghancementGeneral1465SelfTests() -> bool;
auto runCharMoghancementResistance1466SelfTests() -> bool;
auto runCharStartSynth1467SelfTests() -> bool;
auto runCharPacketQueue1468SelfTests() -> bool;
auto runCharEntityUpdate1469SelfTests() -> bool;
auto runCharRuntimeState1470SelfTests() -> bool;
auto runCharTraitSync1471SelfTests() -> bool;
auto runCharAMANHost1472SelfTests() -> bool;
auto runCharRaisePlan1473SelfTests() -> bool;
auto runCharRaiseApply1474SelfTests() -> bool;
auto runCharItemFinishPreflight1475SelfTests() -> bool;
auto runCharItemFinishTargets1476SelfTests() -> bool;
auto runCharItemFinishComplete1477SelfTests() -> bool;
auto runCharTargetResolver1478SelfTests() -> bool;
auto runCharDeathPlan1479SelfTests() -> bool;
auto runCharDeathApply1480SelfTests() -> bool;
auto runCharTimedDeath1481SelfTests() -> bool;
auto runCharRaiseComplete1482SelfTests() -> bool;
auto runCharIsMobOwner1483SelfTests() -> bool;
auto runCharAbilityPreflight1484SelfTests() -> bool;
auto runCharAbilityRecast1485SelfTests() -> bool;
auto runCharAbilityStealth1486SelfTests() -> bool;
auto runCharAbilityParalyze1487SelfTests() -> bool;
auto runCharActivity1488SelfTests() -> bool;
auto runCharShield1489SelfTests() -> bool;
auto runCharGender1490SelfTests() -> bool;
auto runCharAbilityResult1491SelfTests() -> bool;
auto runCharAbilityPet1492SelfTests() -> bool;
auto runCharAbilityResponse1493SelfTests() -> bool;
auto runCharWeaponSkillRange1494SelfTests() -> bool;
auto runCharWeaponSkillSelf1495SelfTests() -> bool;
auto runCharWeaponSkillPrimary1496SelfTests() -> bool;
auto runCharCastFinish1497SelfTests() -> bool;
auto runCharImmanence1498SelfTests() -> bool;
auto runCharCastSkillup1499SelfTests() -> bool;
auto runCharVarCache1500SelfTests() -> bool;
auto runCapacityDistribute1501SelfTests() -> bool;
auto runExpDistribute1502SelfTests() -> bool;
auto runExpAward1504SelfTests() -> bool;
auto runExpLoss1505SelfTests() -> bool;
auto runSkillUp1506SelfTests() -> bool;
auto runCalculateStats1507SelfTests() -> bool;
auto runDistributeGil1508SelfTests() -> bool;
auto runBuildingSkills1509SelfTests() -> bool;
auto runCheckEquipment1510SelfTests() -> bool;
auto runCapacityAward1511SelfTests() -> bool;
auto runWeaponSkillRoster1512SelfTests() -> bool;
auto runAbilityTable1513SelfTests() -> bool;
auto runPetAbilityTable1514SelfTests() -> bool;
auto runKeyItemSpell1515SelfTests() -> bool;
auto runEquipPolicy1516SelfTests() -> bool;
auto runTradeItem1517SelfTests() -> bool;
auto runStyleUpdate1518SelfTests() -> bool;
auto runInventoryMove1519SelfTests() -> bool;
auto runMiscProgress1520SelfTests() -> bool;
auto runEntitySpawn1521SelfTests() -> bool;
auto runZoneOut1522SelfTests() -> bool;
auto runParalyzeShadow1523SelfTests() -> bool;
auto runCombatStatusTails1524SelfTests() -> bool;
auto runClaim1525SelfTests() -> bool;
auto runEnmityCombat1526SelfTests() -> bool;
auto runSpikes1527SelfTests() -> bool;
auto runEntityAction1528SelfTests() -> bool;
auto runTraitsEnmity1529SelfTests() -> bool;
auto runWildCardRandomDeal1530SelfTests() -> bool;
auto runCanAffordSpell1531SelfTests() -> bool;
auto runSpikesStatus1532SelfTests() -> bool;
auto runTakeDamage1533SelfTests() -> bool;
auto runTakePhysical1534SelfTests() -> bool;
auto runTreasureHunterProc1535SelfTests() -> bool;
auto runEnspellHandle1536SelfTests() -> bool;
auto runSkillchainEffect1537SelfTests() -> bool;
auto runTrickAttack1538SelfTests() -> bool;
auto runDrawIn1539SelfTests() -> bool;
auto runEnspellDamageTails1540SelfTests() -> bool;
auto runWeatherGet1541SelfTests() -> bool;
auto runEntityEquip1542SelfTests() -> bool;
auto runWeatherMatches1543SelfTests() -> bool;
auto runBarrage1544SelfTests() -> bool;
auto runScaledItemModifier1545SelfTests() -> bool;
auto runSpellCost1546SelfTests() -> bool;
auto runDmgTaken1547SelfTests() -> bool;
auto runWSTP1548SelfTests() -> bool;
auto runSpellRecast1549SelfTests() -> bool;
auto runSpellCast1550SelfTests() -> bool;
auto runMultiHits1551SelfTests() -> bool;
auto runCritHitRate1552SelfTests() -> bool;
auto runIsIntimidated1553SelfTests() -> bool;
auto runHitCount1554SelfTests() -> bool;
auto runSkillchainTables1555SelfTests() -> bool;
auto runCombatBonusTails1556SelfTests() -> bool;
auto runDamageAffinity1557SelfTests() -> bool;
auto runSkillchainForm1558SelfTests() -> bool;
auto runFSTR1559SelfTests() -> bool;
auto runLoginPacketHelperSelfTests() -> bool;
auto runLoginWorldListPacketSelfTests() -> bool;
auto runMapActionEnumPrimitiveSelfTests() -> bool;
auto runMapConfigConstantsSelfTests() -> bool;
auto runServerVariablePersistence1235SelfTests() -> bool;
auto runZoneCatalogRuntime1231SelfTests() -> bool;
auto runMapZoneEnumPrimitiveSelfTests() -> bool;
auto runSearchAuctionPacketSelfTests() -> bool;
auto runSearchPacketBufferSelfTests() -> bool;
auto runSearchRequestParserSelfTests() -> bool;
auto runSearchSocialPacketSelfTests() -> bool;
auto runMapPacketBasicHeaderSelfTests() -> bool;
auto runWorldCharacterCacheSelfTests() -> bool;
auto runWorldDailyTallySelfTests() -> bool;
auto runWorldGMCallResponse1240SelfTests() -> bool;
auto runWorldGMCallRequest1244SelfTests() -> bool;
auto runWorldGMCallDatabase1245SelfTests() -> bool;
auto runWorldAccountLogin1252SelfTests() -> bool;
auto runWorldCharZone1255SelfTests() -> bool;
auto runWorldCharVarUpdate1256SelfTests() -> bool;
auto runWorldChatMessageTell1257SelfTests() -> bool;
auto runWorldZoneSettingsSelfTests() -> bool;
auto runC2SPacketValidationScalarSelfTests() -> bool;
auto runC2SPacketIDEnumSelfTests() -> bool;
auto runC2SPacketRateLimiterSelfTests() -> bool;
auto runS2CPacketIDEnumSelfTests() -> bool;
auto runC2SPacketBaseHelperSelfTests() -> bool;
auto runMapEmoteEnumSelfTests() -> bool;
auto runMapFourCCExdataEnumSelfTests() -> bool;
auto runMapMsgBasicEnumSelfTests() -> bool;
auto runMapKeyItemEnumSelfTests() -> bool;
auto runMobModifierSelfTests() -> bool;
auto runMobSpellListSelfTests() -> bool;
auto runSchedulerCombinatorSelfTests() -> bool;
auto runC2SGameOKPacketSelfTests() -> bool;
auto runC2SNetEndPacketSelfTests() -> bool;
auto runC2SCLStatPacketSelfTests() -> bool;
auto runC2SZoneTransitionPacketSelfTests() -> bool;
auto runC2SCharReqPacketSelfTests() -> bool;
auto runC2SCharReq2PacketSelfTests() -> bool;
auto runC2SHeaderOnlyRequestPacketSelfTests() -> bool;
auto runC2SCLIStatusPacketSelfTests() -> bool;
auto runC2SFragmentsPacketSelfTests() -> bool;
auto runC2SPosPacketSelfTests() -> bool;
auto runC2SActionPacketSelfTests() -> bool;
auto runC2SFriendPassUnknownPacketSelfTests() -> bool;
auto runC2SItemDumpMovePacketSelfTests() -> bool;
auto runC2SItemLookupPacketSelfTests() -> bool;
auto runC2SPlayerTradePacketSelfTests() -> bool;
auto runC2SItemActionPacketSelfTests() -> bool;
auto runC2SItemContainerOpsPacketSelfTests() -> bool;
auto runC2SBlacklistPacketSelfTests() -> bool;
auto runC2STrophyPacketSelfTests() -> bool;
auto runC2SEventUpdatePacketSelfTests() -> bool;
auto runC2SRecipeMiscPacketSelfTests() -> bool;
auto runC2SMotionMapRectPacketSelfTests() -> bool;
auto runC2SScenarioItemPacketSelfTests() -> bool;
auto runC2SGroupPacketSelfTests() -> bool;
auto runC2SShopPacketSelfTests() -> bool;
auto runC2SCombineAskPacketSelfTests() -> bool;
auto runC2SChocoboRaceReqPacketSelfTests() -> bool;
auto runC2SDicePacketSelfTests() -> bool;
auto runC2SGuildPacketSelfTests() -> bool;
auto runC2SSwitchNominatePacketSelfTests() -> bool;
auto runC2SChatAssistPacketSelfTests() -> bool;
auto runC2SPlayerPointsPacketSelfTests() -> bool;
auto runC2SComlinkMyRoomPacketSelfTests() -> bool;
auto runC2SHelpdeskMapPacketSelfTests() -> bool;
auto runC2SConfigPacketSelfTests() -> bool;
auto runC2SDungeonInspectPacketSelfTests() -> bool;
auto runC2SUserLinkshellMessagePacketSelfTests() -> bool;
auto runC2SLogoutStancePacketSelfTests() -> bool;
auto runC2SRescueBuffSubmapPacketSelfTests() -> bool;
auto runC2STrackingPacketSelfTests() -> bool;
auto runC2SMyRoomFurniturePacketSelfTests() -> bool;
auto runC2SMyRoomPlantPacketSelfTests() -> bool;
auto runC2SMyRoomJobPacketSelfTests() -> bool;
auto runC2SExtendedJobPacketSelfTests() -> bool;
auto runC2SBazaarBuyerPacketSelfTests() -> bool;
auto runC2SBazaarSellerPacketSelfTests() -> bool;
auto runC2SROEPacketSelfTests() -> bool;
auto runC2SCurrencyRequestPacketSelfTests() -> bool;
auto runC2SBattlefieldSitChairPacketSelfTests() -> bool;
auto runBattlefieldSelfTests() -> bool;
auto runC2SUnityPacketSelfTests() -> bool;
auto runC2STailMiscPacketSelfTests() -> bool;
auto runC2SGMPacketSelfTests() -> bool;
auto runC2SLockstylePacketSelfTests() -> bool;
auto runC2SEquipmentPacketSelfTests() -> bool;
auto runC2SFishingPacketSelfTests() -> bool;
auto runC2SPBXPacketSelfTests() -> bool;
auto runC2SAUCPacketSelfTests() -> bool;
auto runC2SLoginPacketSelfTests() -> bool;
auto runS2CLoginPacketSelfTests() -> bool;
auto runS2CHeaderOnlyPacketSelfTests() -> bool;
auto runS2CBallistaPacketSelfTests() -> bool;
auto runS2CAssistPacketSelfTests() -> bool;
auto runS2CAlterEgoPointsPacketSelfTests() -> bool;
auto runS2CAbilRecastPacketSelfTests() -> bool;
auto runS2CAUCPacketSelfTests() -> bool;
auto runS2CBazaarPacketSelfTests() -> bool;
auto runS2CBattle2PacketSelfTests() -> bool;
auto runS2CBattlefieldPacketSelfTests() -> bool;
auto runS2CBattleMessagePacketSelfTests() -> bool;
auto runS2CBlackEditPacketSelfTests() -> bool;
auto runS2CBlackListPacketSelfTests() -> bool;
auto runS2CCharStatusPacketSelfTests() -> bool;
auto runS2CCharSyncPacketSelfTests() -> bool;
auto runS2CCharUpdatePacketSelfTests() -> bool;
auto runS2CChatStdPacketSelfTests() -> bool;
auto runS2CChocoboRacingPacketSelfTests() -> bool;
auto runS2CCliStatusPacketSelfTests() -> bool;
auto runS2CCliStatus2PacketSelfTests() -> bool;
auto runS2CCombinePacketSelfTests() -> bool;
auto runS2CCommandDataPacketSelfTests() -> bool;
auto runS2CConfigPacketSelfTests() -> bool;
auto runS2CConquestPacketSelfTests() -> bool;
auto runS2CCurrencies1PacketSelfTests() -> bool;
auto runS2CCurrencies2PacketSelfTests() -> bool;
auto runS2CEnterZonePacketSelfTests() -> bool;
auto runS2CInfluencePacketSelfTests() -> bool;
auto runS2CJobInfoPacketSelfTests() -> bool;
auto runS2CJobPointsPacketSelfTests() -> bool;
auto runS2CJumpPacketSelfTests() -> bool;
auto runS2CDigPacketSelfTests() -> bool;
auto runS2CDungeonPacketSelfTests() -> bool;
auto runS2CEffectPacketSelfTests() -> bool;
auto runS2CEntityUpdatePacketSelfTests() -> bool;
auto runS2CEventPacketSelfTests() -> bool;
auto runS2CEventUCOffPacketSelfTests() -> bool;
auto runS2CEntitySetNamePacketSelfTests() -> bool;
auto runS2CEntityVisPacketSelfTests() -> bool;
auto runS2CFragmentsFishRankingPacketSelfTests() -> bool;
auto runS2CFragmentsServmesPacketSelfTests() -> bool;
auto runS2CSwitchPacketSelfTests() -> bool;
auto runS2CEventStrPacketSelfTests() -> bool;
auto runS2CEventNumPacketSelfTests() -> bool;
auto runS2CExtendedJobPacketSelfTests() -> bool;
auto runS2CLinkConciergeHeaderPacketSelfTests() -> bool;
auto runS2CLinkConciergeRecordPacketSelfTests() -> bool;
auto runS2CMagicDataPacketSelfTests() -> bool;
auto runS2CMagicSchedulorPacketSelfTests() -> bool;
auto runS2CMapGroupPacketSelfTests() -> bool;
auto runS2CMapSchedulorPacketSelfTests() -> bool;
auto runS2CMeritPacketSelfTests() -> bool;
auto runS2CMiscDataMeritsPacketSelfTests() -> bool;
auto runS2CMiscDataJobPointsPacketSelfTests() -> bool;
auto runS2CMiscDataHomepointsPacketSelfTests() -> bool;
auto runS2CMiscDataMonstrosityPacketSelfTests() -> bool;
auto runS2CMiscDataStatusIconsPacketSelfTests() -> bool;
auto runS2CMiscDataUnknownPacketSelfTests() -> bool;
auto runS2CMiscDataUnityPacketSelfTests() -> bool;
auto runS2CMissionPacketSelfTests() -> bool;
auto runS2CLogoutPacketSelfTests() -> bool;
auto runS2CWeatherPacketSelfTests() -> bool;
auto runS2CShopPacketSelfTests() -> bool;
auto runS2CReqSubmapNumPacketSelfTests() -> bool;
auto runS2CMusicPacketSelfTests() -> bool;
auto runS2CMusicVolumePacketSelfTests() -> bool;
auto runS2CMotionMesPacketSelfTests() -> bool;
auto runS2CMountDataPacketSelfTests() -> bool;
auto runS2CEquipClearPacketSelfTests() -> bool;
auto runS2CEquipListPacketSelfTests() -> bool;
auto runS2CEquipInspectPacketSelfTests() -> bool;
auto runS2CEquipSetValidPacketSelfTests() -> bool;
auto runS2CDefaultPacketSelfTests() -> bool;
auto runS2CEmoteListPacketSelfTests() -> bool;
auto runS2CGroupListPacketSelfTests() -> bool;
auto runS2CGroupList2PacketSelfTests() -> bool;
auto runS2CGroupTblPacketSelfTests() -> bool;
auto runS2CItemAttrPacketSelfTests() -> bool;
auto runS2CItemSearchPacketSelfTests() -> bool;
auto runS2CItemMaxPacketSelfTests() -> bool;
auto runS2CItemListPacketSelfTests() -> bool;
auto runS2CItemNumPacketSelfTests() -> bool;
auto runS2CItemSamePacketSelfTests() -> bool;
auto runS2CItemTradeSessionPacketSelfTests() -> bool;
auto runS2CItemTradePacketSelfTests() -> bool;
auto runS2CItemSubcontainerPacketSelfTests() -> bool;
auto runS2CMyRoomPacketSelfTests() -> bool;
auto runS2CMyRoomOperationPacketSelfTests() -> bool;
auto runS2CPacketControlPacketSelfTests() -> bool;
auto runS2CPBXResultPacketSelfTests() -> bool;
auto runS2CPartyReqPacketSelfTests() -> bool;
auto runS2CPendingNumPacketSelfTests() -> bool;
auto runS2CPendingStrPacketSelfTests() -> bool;
auto runS2CPetSyncPacketSelfTests() -> bool;
auto runS2CFAQGMParamPacketSelfTests() -> bool;
auto runS2CFishPacketSelfTests() -> bool;
auto runS2CFriendPassPacketSelfTests() -> bool;
auto runS2CRecipePacketSelfTests() -> bool;
auto runS2CRegistrationPacketSelfTests() -> bool;
auto runS2CResPacketSelfTests() -> bool;
auto runS2CROEActiveLogPacketSelfTests() -> bool;
auto runS2CROELogPacketSelfTests() -> bool;
auto runS2CScenarioItemPacketSelfTests() -> bool;
auto runS2CUnityPacketSelfTests() -> bool;
auto runS2CGMPacketSelfTests() -> bool;
auto runS2CGMSupportPacketSelfTests() -> bool;
auto runS2CGrapListPacketSelfTests() -> bool;
auto runS2CGroupAttrPacketSelfTests() -> bool;
auto runS2CGroupCheckIDPacketSelfTests() -> bool;
auto runS2CGroupComlinkPacketSelfTests() -> bool;
auto runS2CGroupEffectsPacketSelfTests() -> bool;
auto runS2CGroupSolicitReqPacketSelfTests() -> bool;
auto runS2CGuildListPacketSelfTests() -> bool;
auto runS2CGuildResultPacketSelfTests() -> bool;
auto runS2CInspectMessagePacketSelfTests() -> bool;
auto runS2CLinkshellMessagePacketSelfTests() -> bool;
auto runS2CMessagePacketSelfTests() -> bool;
auto runS2CSchedulorPacketSelfTests() -> bool;
auto runS2CSystemMesPacketSelfTests() -> bool;
auto runS2CTalkNumPacketSelfTests() -> bool;
auto runS2CTalkNumWorkPacketSelfTests() -> bool;
auto runS2CTalkNumWork2PacketSelfTests() -> bool;
auto runS2CTalkNumNamePacketSelfTests() -> bool;
auto runS2CTrophyListPacketSelfTests() -> bool;
auto runS2CTrophySolutionPacketSelfTests() -> bool;
auto runS2CTrackingListPacketSelfTests() -> bool;
auto runS2CTrackingStatePacketSelfTests() -> bool;
auto runS2CTrackingPosPacketSelfTests() -> bool;
auto runS2CTranslatePacketSelfTests() -> bool;
auto runS2CWPosPacketSelfTests() -> bool;

namespace
{
    auto runOmegaSelfTests() -> bool
    {
        bool ok = true;
        ok = runEarthTimeSelfTests() && ok;
        ok = runIPPSelfTests() && ok;
        ok = runBitpackSelfTests() && ok;
        ok = runBlowfishSelfTests() && ok;
        ok = runBlacklistPersistenceRuntimeSelfTests() && ok;
        ok = runDataEnumTraitsSelfTests() && ok;
        ok = runStringCodecSelfTests() && ok;
        ok = runSJISCodecSelfTests() && ok;
        ok = runSpatialOrientationSelfTests() && ok;
        ok = runNumericUtilsSelfTests() && ok;
        ok = runStringUtilsSelfTests() && ok;
        ok = runConsoleServiceInputSelfTests() && ok;
        ok = runLookParserSelfTests() && ok;
        ok = runHashUtilsSelfTests() && ok;
        ok = runRngEnginesSelfTests() && ok;
        ok = runXiBitsetSelfTests() && ok;
        ok = runCircularBufferSelfTests() && ok;
        ok = runCraftStateSelfTests() && ok;
        ok = runTimerHelpersSelfTests() && ok;
        ok = runSynchronizedSelfTests() && ok;
        ok = runTypedFlagsSelfTests() && ok;
        ok = runMaybeOptionalSelfTests() && ok;
        ok = runMMOConfigTypesSelfTests() && ok;
        ok = runMMOEminenceSelfTests() && ok;
        ok = runMMOKeyItemsSelfTests() && ok;
        ok = runMMOProgressLogSelfTests() && ok;
        ok = runMMOSearchBazaarSelfTests() && ok;
        ok = runMMOStatsSkillsSelfTests() && ok;
        ok = runUUIDGenerationSelfTests() && ok;
        ok = runZlibCompressedSizeSelfTests() && ok;
        ok = runZlibCodecSelfTests() && ok;
        ok = runFileUtilsSelfTests() && ok;
        ok = runRateLimitUtilsSelfTests() && ok;
        ok = runEventInfoSelfTests() && ok;
        ok = runLatentEffectSelfTests() && ok;
        ok = runArgumentsParserSelfTests() && ok;
        ok = runAuctionTransactionRuntimeSelfTests() && ok;
        ok = runDeliveryBoxTransactionRuntimeSelfTests() && ok;
        ok = runActionModelSelfTests() && ok;
        ok = runActionQueueSelfTests() && ok;
        ok = runInstanceLifecycleSelfTests() && ok;
        ok = runInstanceUtilsRuntimeSelfTests() && ok;
        ok = runBaseEntityModelSelfTests() && ok;
        ok = runVersionInfoSelfTests() && ok;
        ok = runSingletonHelperSelfTests() && ok;
        ok = runInventorySyncStateSelfTests() && ok;
        ok = runItemAccessSelfTests() && ok;
        ok = runItemContainerSelfTests() && ok;
        ok = runItemCurrencySelfTests() && ok;
        ok = runItemEquipmentSelfTests() && ok;
        ok = runItemExdataSelfTests() && ok;
        ok = runItemFishSelfTests() && ok;
        ok = runItemFlowerpotSelfTests() && ok;
        ok = runItemFurnishingSelfTests() && ok;
        ok = runItemGeneralSelfTests() && ok;
        ok = runItemLinkshellSelfTests() && ok;
        ok = runItemPuppetSelfTests() && ok;
        ok = runItemShopSelfTests() && ok;
        ok = runItemTransactionSelfTests() && ok;
        ok = runItemUsableSelfTests() && ok;
        ok = runItemWeaponSelfTests() && ok;
        ok = runGradesSelfTests() && ok;
        ok = runGuildPatternRuntimeSelfTests() && ok;
        ok = runBlueMagicSetRuntime1233SelfTests() && ok;
        ok = runTradeContainerSelfTests() && ok;
        ok = runUniversalContainerSelfTests() && ok;
        ok = runRecastContainerSelfTests() && ok;
        ok = runTraitSelfTests() && ok;
        ok = runJobPointsSelfTests() && ok;
        ok = runEnmityContainerSelfTests() && ok;
        ok = runModifierSelfTests() && ok;
        ok = runMazeSelfTests() && ok;
        ok = runNotorietyContainerSelfTests() && ok;
        ok = runSpawnSlotSelfTests() && ok;
        ok = runStatusEffectModelSelfTests() && ok;
        ok = runStatusEffectContainerSelfTests() && ok;
        ok = runStatusEffectDataSelfTests() && ok;
        ok = runTimeTriggerSelfTests() && ok;
        ok = runTransportRuntimeSelfTests() && ok;
        ok = runSpatialGridSelfTests() && ok;
        ok = runXimeshMathSelfTests() && ok;
        ok = runXimeshStructsSelfTests() && ok;
        ok = runXimeshNullMeshSelfTests() && ok;
        ok = runDatabaseQueryHelpersSelfTests() && ok;
        ok = runLoggingUntrustedStringsSelfTests() && ok;
        ok = runLoggingBacktraceBufferSelfTests() && ok;
        ok = runLoginMalformedStringSelfTests() && ok;
        ok = runLoginCertHelpersSelfTests() && ok;
        ok = runLoginDisplayBitmasksSelfTests() && ok;
        ok = runLoginErrorPacketSelfTests() && ok;
        ok = runLoginOTPHelpersSelfTests() && ok;
        ok = runSettingsNumberHelperSelfTests() && ok;
        ok = runSettingsValueConversionsSelfTests() && ok;
        ok = runSettingsLoaderSelfTests() && ok;
        ok = runLOSCacheSelfTests() && ok;
        ok = runLinkshellSelfTests() && ok;
        ok = runMapStatisticsSelfTests() && ok;
        ok = runLoginPacketHashSelfTests() && ok;
        ok = runLoginJSONGetSelfTests() && ok;
        ok = runLoginKeyPacketSelfTests() && ok;
        ok = runLoginVersionLockSelfTests() && ok;
        ok = runMapNetworkPacketBuildingSelfTests() && ok;
        ok = runMapSessionBlowfishSelfTests() && ok;
        ok = runMapSessionIndexSelfTests() && ok;
        ok = runSQLiteQueryTranslationSelfTests() && ok;
        ok = runWorldCharacterCacheSelfTests() && ok;
        ok = runWorldDailyTallySelfTests() && ok;
        ok = runWorldGMCallResponse1240SelfTests() && ok;
        ok = runWorldGMCallRequest1244SelfTests() && ok;
        ok = runWorldGMCallDatabase1245SelfTests() && ok;
        ok = runWorldAccountLogin1252SelfTests() && ok;
        ok = runWorldCharZone1255SelfTests() && ok;
        ok = runWorldCharVarUpdate1256SelfTests() && ok;
        ok = runWorldChatMessageTell1257SelfTests() && ok;
        ok = runWorldZoneSettingsSelfTests() && ok;
        ok = runMariaDBConnectionLossSelfTests() && ok;
        ok = runMariaDBResultCellConversionsSelfTests() && ok;
        ok = runMariaDBResultSetMetadataSelfTests() && ok;
        ok = runResultSetTypedGettersSelfTests() && ok;
        ok = runDatabaseBindingSelfTests() && ok;
        ok = runActiveDatabaseDispatchSelfTests() && ok;
        ok = runDatabaseConvenienceHelpersSelfTests() && ok;
        ok = runCachingDatabaseSelfTests() && ok;
        ok = runIPCChannelSelfTests() && ok;
        ok = runZmqEndpointOpenedSelfTests() && ok;
        ok = runFilewatcherQueueSelfTests() && ok;
        ok = runGardenResultRuntimeSelfTests() && ok;
        ok = runLoggingJsonRendererSelfTests() && ok;
        ok = runLoggingContextStackSelfTests() && ok;
        ok = runXirandHelpersSelfTests() && ok;
        ok = runIPCMessageTypeSelfTests() && ok;
        ok = runIPCChatPayloadSelfTests() && ok;
        ok = runIPCDispatch1248SelfTests() && ok;
        ok = runIPCSessionPayloadSelfTests() && ok;
        ok = runIPCPartyPayloadSelfTests() && ok;
        ok = runIPCLinkshellPayloadSelfTests() && ok;
        ok = runIPCGMCallPayloadSelfTests() && ok;
        ok = runGMCallAssembly1238SelfTests() && ok;
        ok = runGMCallPendingResponse1239SelfTests() && ok;
        ok = runGMCallPacketHandlers1242SelfTests() && ok;
        ok = runGMCallPersistence1243SelfTests() && ok;
        ok = runMapGMCallResponseNotification1241SelfTests() && ok;
        ok = runMapAccountLogin1253SelfTests() && ok;
        ok = runMapCharZone1254SelfTests() && ok;
        ok = runMapCharVarUpdate1256SelfTests() && ok;
        ok = runMapChatMessageTell1258SelfTests() && ok;
        ok = runMapAssistChannelEvent1290SelfTests() && ok;
        ok = runMapPlayerRelocation1291SelfTests() && ok;
        ok = runMapEntityInformationRequest1292SelfTests() && ok;
        ok = runMapStandardMessageDelivery1293SelfTests() && ok;
        ok = runMapPlayerKickRefresh1294SelfTests() && ok;
        ok = runMapPartyAllianceUpdates1295SelfTests() && ok;
        ok = runMapLinkshellUpdates1296SelfTests() && ok;
        ok = runMapGroupChatDelivery1297SelfTests() && ok;
        ok = runMapZoneWideChatDelivery1298SelfTests() && ok;
        ok = runMapChatMessageCustom1299SelfTests() && ok;
        ok = runMapPartyInvite1300SelfTests() && ok;
        ok = runMapKillSession1301SelfTests() && ok;
        ok = runMapRegionalEventDispatch1302SelfTests() && ok;
        ok = runMapPartyInviteResponse1303SelfTests() && ok;
        ok = runMapLuaFunction1304SelfTests() && ok;
        ok = runMapIPCDiagnostics1305SelfTests() && ok;
        ok = runMapGMCallRequest1306SelfTests() && ok;
        ok = runWorldChatMessageParty1259SelfTests() && ok;
        ok = runWorldChatMessageAlliance1260SelfTests() && ok;
        ok = runWorldChatMessageLinkshell1261SelfTests() && ok;
        ok = runWorldChatMessageUnity1262SelfTests() && ok;
        ok = runWorldChatMessageYell1263SelfTests() && ok;
        ok = runWorldChatMessageAssist1264SelfTests() && ok;
        ok = runWorldChatMessageServerMessage1265SelfTests() && ok;
        ok = runWorldChatMessageCustom1266SelfTests() && ok;
        ok = runWorldPartyInvite1267SelfTests() && ok;
        ok = runWorldPartyInviteResponse1268SelfTests() && ok;
        ok = runWorldPartyReload1269SelfTests() && ok;
        ok = runWorldPartyDisband1270SelfTests() && ok;
        ok = runWorldAllianceReload1271SelfTests() && ok;
        ok = runWorldAllianceDissolve1272SelfTests() && ok;
        ok = runWorldPlayerKick1273SelfTests() && ok;
        ok = runWorldMessageStandard1274SelfTests() && ok;
        ok = runWorldMessageSystem1275SelfTests() && ok;
        ok = runWorldLinkshellRankChange1276SelfTests() && ok;
        ok = runWorldLinkshellRemove1277SelfTests() && ok;
        ok = runWorldLinkshellSetMessage1278SelfTests() && ok;
        ok = runWorldLuaFunction1279SelfTests() && ok;
        ok = runWorldKillSession1280SelfTests() && ok;
        ok = runWorldConquestEvent1281SelfTests() && ok;
        ok = runWorldBesiegedEvent1282SelfTests() && ok;
        ok = runWorldCampaignEvent1283SelfTests() && ok;
        ok = runWorldColonizationEvent1284SelfTests() && ok;
        ok = runWorldEntityInformationRequest1285SelfTests() && ok;
        ok = runWorldEntityInformationResponse1286SelfTests() && ok;
        ok = runWorldSendPlayerToLocation1287SelfTests() && ok;
        ok = runWorldAssistChannelEvent1288SelfTests() && ok;
        ok = runWorldIPCDiagnostics1289SelfTests() && ok;
        ok = runIPCRegionalPayloadSelfTests() && ok;
        ok = runIPCStandardMessagePayloadSelfTests() && ok;
        ok = runIPCMessageFramingSelfTests() && ok;
        ok = runTracyHexHelperSelfTests() && ok;
        ok = runTriggerAreaSelfTests() && ok;
        ok = runTreasurePoolResolutionSelfTests() && ok;
        ok = runWeatherContainerSelfTests() && ok;
        ok = runMapEnumPrimitiveSelfTests() && ok;
        ok = runMountStateRuntime1234SelfTests() && ok;
        ok = runLoginErrorCodeSelfTests() && ok;
        ok = runLoginAuthConstantSelfTests() && ok;
        ok = runLoginAuthPassword1307SelfTests() && ok;
        ok = runLoginAuthVersionError1308SelfTests() && ok;
        ok = runLoginAuthAccountID1309SelfTests() && ok;
        ok = runLoginAuthAccountCreate1310SelfTests() && ok;
        ok = runLoginAuthChangePassword1311SelfTests() && ok;
        ok = runLoginAuthTOTPURI1312SelfTests() && ok;
        ok = runLoginAuthOTPRecovery1313SelfTests() && ok;
        ok = runLoginAuthLoginAttemptOTP1314SelfTests() && ok;
        ok = runLoginAuthSuccessReply1315SelfTests() && ok;
        ok = runLoginCharacterName1316SelfTests() && ok;
        ok = runLoginViewLobbyAck1317SelfTests() && ok;
        ok = runLoginCharacterSelect1318SelfTests() && ok;
        ok = runLoginCharacterDelete1319SelfTests() && ok;
        ok = runLoginCharacterCreate1320SelfTests() && ok;
        ok = runLoginViewAcquirePlayer1321SelfTests() && ok;
        ok = runLoginSessionCleanup1322SelfTests() && ok;
        ok = runLoginDataA11323SelfTests() && ok;
        ok = runLoginDataA21324SelfTests() && ok;
        ok = runLoginConnectCleanup1325SelfTests() && ok;
        ok = runLoginConnectConsole1326SelfTests() && ok;
        ok = runPartyCapacity1327SelfTests() && ok;
        ok = runPartyMemberCount1328SelfTests() && ok;
        ok = runAllianceCapacity1329SelfTests() && ok;
        ok = runPartyLevelSync1330SelfTests() && ok;
        ok = runLoginConnectApp1331SelfTests() && ok;
        ok = runMapAppConfig1332SelfTests() && ok;
        ok = runWorldAppConfig1333SelfTests() && ok;
        ok = runPartySetSyncTarget1334SelfTests() && ok;
        ok = runPartyPushPacket1335SelfTests() && ok;
        ok = runPartyGroupEffects1336SelfTests() && ok;
        ok = runMapGMConsole1337SelfTests() && ok;
        ok = runMapEngineConfig1338SelfTests() && ok;
        ok = runAllianceDissolve1339SelfTests() && ok;
        ok = runPartyRemoveLeader1340SelfTests() && ok;
        ok = runAllianceRemoveParty1341SelfTests() && ok;
        ok = runMapMainExit1342SelfTests() && ok;
        ok = runFixedMainExit1343SelfTests() && ok;
        ok = runSearchMainExit1344SelfTests() && ok;
        ok = runPartyDisband1345SelfTests() && ok;
        ok = runAllianceAssignLeader1346SelfTests() && ok;
        ok = runPartyAssignRole1347SelfTests() && ok;
        ok = runPartyMemberLookup1348SelfTests() && ok;
        ok = runPartyRemoveMember1349SelfTests() && ok;
        ok = runPartyAddMember1350SelfTests() && ok;
        ok = runPartyPushPopDel1351SelfTests() && ok;
        ok = runPartyReload1352SelfTests() && ok;
        ok = runPartyMemberFlags1353SelfTests() && ok;
        ok = runLinkshellCapacity1354SelfTests() && ok;
        ok = runLinkshellRegistry1355SelfTests() && ok;
        ok = runUnityChatCapacity1356SelfTests() && ok;
        ok = runGuildPointsMath1358SelfTests() && ok;
        ok = runLatentConditionEval1359SelfTests() && ok;
        ok = runLatentConditionEval1360SelfTests() && ok;
        ok = runBattlefieldPolicy1361SelfTests() && ok;
        ok = runSpawnCanSpawn1362SelfTests() && ok;
        ok = runZonePolicy1363SelfTests() && ok;
        ok = runStatusEffectCanGain1364SelfTests() && ok;
        ok = runStatusEffectSelection1365SelfTests() && ok;
        ok = runStatusEffectTick1366SelfTests() && ok;
        ok = runTreasurePoolPolicy1367SelfTests() && ok;
        ok = runStatusEffectPrevent1368SelfTests() && ok;
        ok = runStatusEffectParams1369SelfTests() && ok;
        ok = runRecastCharge1370SelfTests() && ok;
        ok = runStatusEffectAddRemove1371SelfTests() && ok;
        ok = runStatusEffectDelete1372SelfTests() && ok;
        ok = runStatusEffectSave1373SelfTests() && ok;
        ok = runAttackRoundMultihit1374SelfTests() && ok;
        ok = runAttackRoundFollowUp1375SelfTests() && ok;
        ok = runAttackChecks1376SelfTests() && ok;
        ok = runAttackDamage1377SelfTests() && ok;
        ok = runAttackAssembly1378SelfTests() && ok;
        ok = runAttackHitRate1379SelfTests() && ok;
        ok = runAttackutilsMultiplier1380SelfTests() && ok;
        ok = runRangeState1381SelfTests() && ok;
        ok = runMagicState1382SelfTests() && ok;
        ok = runAbilityState1383SelfTests() && ok;
        ok = runWeaponSkillState1384SelfTests() && ok;
        ok = runMobSkillState1385SelfTests() && ok;
        ok = runPetSkillState1386SelfTests() && ok;
        ok = runAttackState1387SelfTests() && ok;
        ok = runCanAttack1388SelfTests() && ok;
        ok = runRangedHitCount1389SelfTests() && ok;
        ok = runRangedAmmo1390SelfTests() && ok;
        ok = runCamouflageRetain1391SelfTests() && ok;
        ok = runRangedAdditionalEffect1392SelfTests() && ok;
        ok = runRangedOutcome1393SelfTests() && ok;
        ok = runRangedActorFinalize1394SelfTests() && ok;
        ok = runDisengage1395SelfTests() && ok;
        ok = runAttackEntry1396SelfTests() && ok;
        ok = runAttackSwingGate1397SelfTests() && ok;
        ok = runAttackHitPath1398SelfTests() && ok;
        ok = runAttackPostSwing1399SelfTests() && ok;
        ok = runZanshin1400SelfTests() && ok;
        ok = runDakenSangeAmmo1401SelfTests() && ok;
        ok = runAttackLoop1402SelfTests() && ok;
        ok = runEngage1403SelfTests() && ok;
        ok = runDespawnFinalize1404SelfTests() && ok;
        ok = runPostTickDeath1405SelfTests() && ok;
        ok = runHitInterrupt1406SelfTests() && ok;
        ok = runBattleTime1407SelfTests() && ok;
        ok = runBattleIdentity1408SelfTests() && ok;
        ok = runEnmityPresence1409SelfTests() && ok;
        ok = runDeathFinalize1410SelfTests() && ok;
        ok = runBattleSpawn1411SelfTests() && ok;
        ok = runMobDeath1412SelfTests() && ok;
        ok = runMobDeathReward1413SelfTests() && ok;
        ok = runPetDeath1414SelfTests() && ok;
        ok = runTrustDeath1415SelfTests() && ok;
        ok = runAutomatonDeath1416SelfTests() && ok;
        ok = runPetSpawn1417SelfTests() && ok;
        ok = runTrustSpawn1418SelfTests() && ok;
        ok = runPetZoningRestore1419SelfTests() && ok;
        ok = runPetPostTick1420SelfTests() && ok;
        ok = runAutomatonPostTick1421SelfTests() && ok;
        ok = runPetFadeOut1422SelfTests() && ok;
        ok = runTrustFadeOut1423SelfTests() && ok;
        ok = runTrustPostTick1424SelfTests() && ok;
        ok = runTrustDespawn1425SelfTests() && ok;
        ok = runTrustCastFinished1426SelfTests() && ok;
        ok = runTrustValidTarget1427SelfTests() && ok;
        ok = runPetValidTarget1428SelfTests() && ok;
        ok = runPetJugTimer1429SelfTests() && ok;
        ok = runPetCanAttack1430SelfTests() && ok;
        ok = runPetAbility1431SelfTests() && ok;
        ok = runPetAbilityResult1432SelfTests() && ok;
        ok = runPetConstruction1433SelfTests() && ok;
        ok = runCharPetZoning1434SelfTests() && ok;
        ok = runCharAutomaton1435SelfTests() && ok;
        ok = runCharStorage1436SelfTests() && ok;
        ok = runCharPlaytime1437SelfTests() && ok;
        ok = runCharBazaar1438SelfTests() && ok;
        ok = runCharName1439SelfTests() && ok;
        ok = runCharResource1440SelfTests() && ok;
        ok = runCharEquipment1441SelfTests() && ok;
        ok = runCharTrustRoster1442SelfTests() && ok;
        ok = runCharPersistence1443SelfTests() && ok;
        ok = runCharTick1444SelfTests() && ok;
        ok = runCharPostTickRefresh1445SelfTests() && ok;
        ok = runCharPostTickUpdate1446SelfTests() && ok;
        ok = runCharEquipFlush1447SelfTests() && ok;
        ok = runCharValidTarget1448SelfTests() && ok;
        ok = runCharCombatTransition1449SelfTests() && ok;
        ok = runCharActionBoundary1450SelfTests() && ok;
        ok = runCharErrorDelivery1451SelfTests() && ok;
        ok = runCharDeathHomepoint1452SelfTests() && ok;
        ok = runCharTriggerArea1453SelfTests() && ok;
        ok = runCharEventLock1454SelfTests() && ok;
        ok = runCharEventQueue1455SelfTests() && ok;
        ok = runCharEventSkip1456SelfTests() && ok;
        ok = runCharEventIdle1457SelfTests() && ok;
        ok = runCharEventActivation1458SelfTests() && ok;
        ok = runCharEventPacket1459SelfTests() && ok;
        ok = runCharHighestJob1460SelfTests() && ok;
        ok = runCharMoghancementState1461SelfTests() && ok;
        ok = runCharMoghancementFurniture1462SelfTests() && ok;
        ok = runCharMoghancementUpdate1463SelfTests() && ok;
        ok = runCharMoghancementCraft1464SelfTests() && ok;
        ok = runCharMoghancementGeneral1465SelfTests() && ok;
        ok = runCharMoghancementResistance1466SelfTests() && ok;
        ok = runCharStartSynth1467SelfTests() && ok;
        ok = runCharPacketQueue1468SelfTests() && ok;
        ok = runCharEntityUpdate1469SelfTests() && ok;
        ok = runCharRuntimeState1470SelfTests() && ok;
        ok = runCharTraitSync1471SelfTests() && ok;
        ok = runCharAMANHost1472SelfTests() && ok;
        ok = runCharRaisePlan1473SelfTests() && ok;
        ok = runCharRaiseApply1474SelfTests() && ok;
        ok = runCharItemFinishPreflight1475SelfTests() && ok;
        ok = runCharItemFinishTargets1476SelfTests() && ok;
        ok = runCharItemFinishComplete1477SelfTests() && ok;
        ok = runCharTargetResolver1478SelfTests() && ok;
        ok = runCharDeathPlan1479SelfTests() && ok;
        ok = runCharDeathApply1480SelfTests() && ok;
        ok = runCharTimedDeath1481SelfTests() && ok;
        ok = runCharRaiseComplete1482SelfTests() && ok;
        ok = runCharIsMobOwner1483SelfTests() && ok;
        ok = runCharAbilityPreflight1484SelfTests() && ok;
        ok = runCharAbilityRecast1485SelfTests() && ok;
        ok = runCharAbilityStealth1486SelfTests() && ok;
        ok = runCharAbilityParalyze1487SelfTests() && ok;
        ok = runCharActivity1488SelfTests() && ok;
        ok = runCharShield1489SelfTests() && ok;
        ok = runCharGender1490SelfTests() && ok;
        ok = runCharAbilityResult1491SelfTests() && ok;
        ok = runCharAbilityPet1492SelfTests() && ok;
        ok = runCharAbilityResponse1493SelfTests() && ok;
        ok = runCharWeaponSkillRange1494SelfTests() && ok;
        ok = runCharWeaponSkillSelf1495SelfTests() && ok;
        ok = runCharWeaponSkillPrimary1496SelfTests() && ok;
        ok = runCharCastFinish1497SelfTests() && ok;
        ok = runCharImmanence1498SelfTests() && ok;
        ok = runCharCastSkillup1499SelfTests() && ok;
        ok = runCharVarCache1500SelfTests() && ok;
        ok = runCapacityDistribute1501SelfTests() && ok;
        ok = runExpDistribute1502SelfTests() && ok;
        ok = runExpAward1504SelfTests() && ok;
        ok = runExpLoss1505SelfTests() && ok;
        ok = runSkillUp1506SelfTests() && ok;
        ok = runCalculateStats1507SelfTests() && ok;
        ok = runDistributeGil1508SelfTests() && ok;
        ok = runBuildingSkills1509SelfTests() && ok;
        ok = runCheckEquipment1510SelfTests() && ok;
        ok = runCapacityAward1511SelfTests() && ok;
        ok = runWeaponSkillRoster1512SelfTests() && ok;
        ok = runAbilityTable1513SelfTests() && ok;
        ok = runPetAbilityTable1514SelfTests() && ok;
        ok = runKeyItemSpell1515SelfTests() && ok;
        ok = runEquipPolicy1516SelfTests() && ok;
        ok = runTradeItem1517SelfTests() && ok;
        ok = runStyleUpdate1518SelfTests() && ok;
        ok = runInventoryMove1519SelfTests() && ok;
        ok = runMiscProgress1520SelfTests() && ok;
        ok = runEntitySpawn1521SelfTests() && ok;
        ok = runZoneOut1522SelfTests() && ok;
        ok = runParalyzeShadow1523SelfTests() && ok;
        ok = runCombatStatusTails1524SelfTests() && ok;
        ok = runClaim1525SelfTests() && ok;
        ok = runEnmityCombat1526SelfTests() && ok;
        ok = runSpikes1527SelfTests() && ok;
        ok = runEntityAction1528SelfTests() && ok;
        ok = runTraitsEnmity1529SelfTests() && ok;
        ok = runWildCardRandomDeal1530SelfTests() && ok;
        ok = runCanAffordSpell1531SelfTests() && ok;
        ok = runSpikesStatus1532SelfTests() && ok;
        ok = runTakeDamage1533SelfTests() && ok;
        ok = runTakePhysical1534SelfTests() && ok;
        ok = runTreasureHunterProc1535SelfTests() && ok;
        ok = runEnspellHandle1536SelfTests() && ok;
        ok = runSkillchainEffect1537SelfTests() && ok;
        ok = runTrickAttack1538SelfTests() && ok;
        ok = runDrawIn1539SelfTests() && ok;
        ok = runEnspellDamageTails1540SelfTests() && ok;
        ok = runWeatherGet1541SelfTests() && ok;
        ok = runEntityEquip1542SelfTests() && ok;
        ok = runWeatherMatches1543SelfTests() && ok;
        ok = runBarrage1544SelfTests() && ok;
        ok = runScaledItemModifier1545SelfTests() && ok;
        ok = runSpellCost1546SelfTests() && ok;
        ok = runDmgTaken1547SelfTests() && ok;
        ok = runWSTP1548SelfTests() && ok;
        ok = runSpellRecast1549SelfTests() && ok;
        ok = runSpellCast1550SelfTests() && ok;
        ok = runMultiHits1551SelfTests() && ok;
        ok = runCritHitRate1552SelfTests() && ok;
        ok = runIsIntimidated1553SelfTests() && ok;
        ok = runHitCount1554SelfTests() && ok;
        ok = runSkillchainTables1555SelfTests() && ok;
        ok = runCombatBonusTails1556SelfTests() && ok;
        ok = runDamageAffinity1557SelfTests() && ok;
        ok = runSkillchainForm1558SelfTests() && ok;
        ok = runFSTR1559SelfTests() && ok;
        ok = runLoginPacketHelperSelfTests() && ok;
        ok = runLoginWorldListPacketSelfTests() && ok;
        ok = runMapActionEnumPrimitiveSelfTests() && ok;
        ok = runMapConfigConstantsSelfTests() && ok;
        ok = runServerVariablePersistence1235SelfTests() && ok;
        ok = runZoneCatalogRuntime1231SelfTests() && ok;
        ok = runMapZoneEnumPrimitiveSelfTests() && ok;
        ok = runSearchAuctionPacketSelfTests() && ok;
        ok = runSearchPacketBufferSelfTests() && ok;
        ok = runSearchRequestParserSelfTests() && ok;
        ok = runSearchSocialPacketSelfTests() && ok;
        ok = runMapPacketBasicHeaderSelfTests() && ok;
        ok = runC2SPacketValidationScalarSelfTests() && ok;
        ok = runC2SPacketIDEnumSelfTests() && ok;
        ok = runC2SPacketRateLimiterSelfTests() && ok;
        ok = runS2CPacketIDEnumSelfTests() && ok;
        ok = runC2SPacketBaseHelperSelfTests() && ok;
        ok = runMapEmoteEnumSelfTests() && ok;
        ok = runMapFourCCExdataEnumSelfTests() && ok;
        ok = runMapMsgBasicEnumSelfTests() && ok;
        ok = runMapKeyItemEnumSelfTests() && ok;
        ok = runMobModifierSelfTests() && ok;
        ok = runMobSpellListSelfTests() && ok;
        ok = runSchedulerCombinatorSelfTests() && ok;
        ok = runC2SGameOKPacketSelfTests() && ok;
        ok = runC2SNetEndPacketSelfTests() && ok;
        ok = runC2SCLStatPacketSelfTests() && ok;
        ok = runC2SZoneTransitionPacketSelfTests() && ok;
        ok = runC2SCharReqPacketSelfTests() && ok;
        ok = runC2SCharReq2PacketSelfTests() && ok;
        ok = runC2SHeaderOnlyRequestPacketSelfTests() && ok;
        ok = runC2SCLIStatusPacketSelfTests() && ok;
        ok = runC2SFragmentsPacketSelfTests() && ok;
        ok = runC2SPosPacketSelfTests() && ok;
        ok = runC2SActionPacketSelfTests() && ok;
        ok = runC2SFriendPassUnknownPacketSelfTests() && ok;
        ok = runC2SItemDumpMovePacketSelfTests() && ok;
        ok = runC2SItemLookupPacketSelfTests() && ok;
        ok = runC2SPlayerTradePacketSelfTests() && ok;
        ok = runC2SItemActionPacketSelfTests() && ok;
        ok = runC2SItemContainerOpsPacketSelfTests() && ok;
        ok = runC2SBlacklistPacketSelfTests() && ok;
        ok = runC2STrophyPacketSelfTests() && ok;
        ok = runC2SEventUpdatePacketSelfTests() && ok;
        ok = runC2SRecipeMiscPacketSelfTests() && ok;
        ok = runC2SMotionMapRectPacketSelfTests() && ok;
        ok = runC2SScenarioItemPacketSelfTests() && ok;
        ok = runC2SGroupPacketSelfTests() && ok;
        ok = runC2SShopPacketSelfTests() && ok;
        ok = runC2SCombineAskPacketSelfTests() && ok;
        ok = runC2SChocoboRaceReqPacketSelfTests() && ok;
        ok = runC2SDicePacketSelfTests() && ok;
        ok = runC2SGuildPacketSelfTests() && ok;
        ok = runC2SSwitchNominatePacketSelfTests() && ok;
        ok = runC2SChatAssistPacketSelfTests() && ok;
        ok = runC2SPlayerPointsPacketSelfTests() && ok;
        ok = runC2SComlinkMyRoomPacketSelfTests() && ok;
        ok = runC2SHelpdeskMapPacketSelfTests() && ok;
        ok = runC2SConfigPacketSelfTests() && ok;
        ok = runC2SDungeonInspectPacketSelfTests() && ok;
        ok = runC2SUserLinkshellMessagePacketSelfTests() && ok;
        ok = runC2SLogoutStancePacketSelfTests() && ok;
        ok = runC2SRescueBuffSubmapPacketSelfTests() && ok;
        ok = runC2STrackingPacketSelfTests() && ok;
        ok = runC2SMyRoomFurniturePacketSelfTests() && ok;
        ok = runC2SMyRoomPlantPacketSelfTests() && ok;
        ok = runC2SMyRoomJobPacketSelfTests() && ok;
        ok = runC2SExtendedJobPacketSelfTests() && ok;
        ok = runC2SBazaarBuyerPacketSelfTests() && ok;
        ok = runC2SBazaarSellerPacketSelfTests() && ok;
        ok = runC2SROEPacketSelfTests() && ok;
        ok = runC2SCurrencyRequestPacketSelfTests() && ok;
        ok = runC2SBattlefieldSitChairPacketSelfTests() && ok;
        ok = runBattlefieldSelfTests() && ok;
        ok = runC2SUnityPacketSelfTests() && ok;
        ok = runC2STailMiscPacketSelfTests() && ok;
        ok = runC2SGMPacketSelfTests() && ok;
        ok = runC2SLockstylePacketSelfTests() && ok;
        ok = runC2SEquipmentPacketSelfTests() && ok;
        ok = runC2SFishingPacketSelfTests() && ok;
        ok = runC2SPBXPacketSelfTests() && ok;
        ok = runC2SAUCPacketSelfTests() && ok;
        ok = runC2SLoginPacketSelfTests() && ok;
        ok = runS2CLoginPacketSelfTests() && ok;
        ok = runS2CHeaderOnlyPacketSelfTests() && ok;
        ok = runS2CBallistaPacketSelfTests() && ok;
        ok = runS2CAssistPacketSelfTests() && ok;
        ok = runS2CAlterEgoPointsPacketSelfTests() && ok;
        ok = runS2CAbilRecastPacketSelfTests() && ok;
        ok = runS2CAUCPacketSelfTests() && ok;
        ok = runS2CBazaarPacketSelfTests() && ok;
        ok = runS2CBattle2PacketSelfTests() && ok;
        ok = runS2CBattlefieldPacketSelfTests() && ok;
        ok = runS2CBattleMessagePacketSelfTests() && ok;
        ok = runS2CBlackEditPacketSelfTests() && ok;
        ok = runS2CBlackListPacketSelfTests() && ok;
        ok = runS2CCharStatusPacketSelfTests() && ok;
        ok = runS2CCharSyncPacketSelfTests() && ok;
        ok = runS2CCharUpdatePacketSelfTests() && ok;
        ok = runS2CChatStdPacketSelfTests() && ok;
        ok = runS2CChocoboRacingPacketSelfTests() && ok;
        ok = runS2CCliStatusPacketSelfTests() && ok;
        ok = runS2CCliStatus2PacketSelfTests() && ok;
        ok = runS2CCombinePacketSelfTests() && ok;
        ok = runS2CCommandDataPacketSelfTests() && ok;
        ok = runS2CConfigPacketSelfTests() && ok;
        ok = runS2CConquestPacketSelfTests() && ok;
        ok = runS2CCurrencies1PacketSelfTests() && ok;
        ok = runS2CCurrencies2PacketSelfTests() && ok;
        ok = runS2CEnterZonePacketSelfTests() && ok;
        ok = runS2CInfluencePacketSelfTests() && ok;
        ok = runS2CJobInfoPacketSelfTests() && ok;
        ok = runS2CJobPointsPacketSelfTests() && ok;
        ok = runS2CJumpPacketSelfTests() && ok;
        ok = runS2CDigPacketSelfTests() && ok;
        ok = runS2CDungeonPacketSelfTests() && ok;
        ok = runS2CEffectPacketSelfTests() && ok;
        ok = runS2CEntityUpdatePacketSelfTests() && ok;
        ok = runS2CEventPacketSelfTests() && ok;
        ok = runS2CEventUCOffPacketSelfTests() && ok;
        ok = runS2CEntitySetNamePacketSelfTests() && ok;
        ok = runS2CEntityVisPacketSelfTests() && ok;
        ok = runS2CFragmentsFishRankingPacketSelfTests() && ok;
        ok = runS2CFragmentsServmesPacketSelfTests() && ok;
        ok = runS2CSwitchPacketSelfTests() && ok;
        ok = runS2CEventStrPacketSelfTests() && ok;
        ok = runS2CEventNumPacketSelfTests() && ok;
        ok = runS2CExtendedJobPacketSelfTests() && ok;
        ok = runS2CLinkConciergeHeaderPacketSelfTests() && ok;
        ok = runS2CLinkConciergeRecordPacketSelfTests() && ok;
        ok = runS2CMagicDataPacketSelfTests() && ok;
        ok = runS2CMagicSchedulorPacketSelfTests() && ok;
        ok = runS2CMapGroupPacketSelfTests() && ok;
        ok = runS2CMapSchedulorPacketSelfTests() && ok;
        ok = runS2CMeritPacketSelfTests() && ok;
        ok = runS2CMiscDataMeritsPacketSelfTests() && ok;
        ok = runS2CMiscDataJobPointsPacketSelfTests() && ok;
        ok = runS2CMiscDataHomepointsPacketSelfTests() && ok;
        ok = runS2CMiscDataMonstrosityPacketSelfTests() && ok;
        ok = runS2CMiscDataStatusIconsPacketSelfTests() && ok;
        ok = runS2CMiscDataUnknownPacketSelfTests() && ok;
        ok = runS2CMiscDataUnityPacketSelfTests() && ok;
        ok = runS2CMissionPacketSelfTests() && ok;
        ok = runS2CLogoutPacketSelfTests() && ok;
        ok = runS2CWeatherPacketSelfTests() && ok;
        ok = runS2CShopPacketSelfTests() && ok;
        ok = runS2CReqSubmapNumPacketSelfTests() && ok;
        ok = runS2CMusicPacketSelfTests() && ok;
        ok = runS2CMusicVolumePacketSelfTests() && ok;
        ok = runS2CMotionMesPacketSelfTests() && ok;
        ok = runS2CMountDataPacketSelfTests() && ok;
        ok = runS2CEquipClearPacketSelfTests() && ok;
        ok = runS2CEquipListPacketSelfTests() && ok;
        ok = runS2CEquipInspectPacketSelfTests() && ok;
        ok = runS2CEquipSetValidPacketSelfTests() && ok;
        ok = runS2CDefaultPacketSelfTests() && ok;
        ok = runS2CEmoteListPacketSelfTests() && ok;
        ok = runS2CGroupListPacketSelfTests() && ok;
        ok = runS2CGroupList2PacketSelfTests() && ok;
        ok = runS2CGroupTblPacketSelfTests() && ok;
        ok = runS2CItemAttrPacketSelfTests() && ok;
        ok = runS2CItemSearchPacketSelfTests() && ok;
        ok = runS2CItemMaxPacketSelfTests() && ok;
        ok = runS2CItemListPacketSelfTests() && ok;
        ok = runS2CItemNumPacketSelfTests() && ok;
        ok = runS2CItemSamePacketSelfTests() && ok;
        ok = runS2CItemTradeSessionPacketSelfTests() && ok;
        ok = runS2CItemTradePacketSelfTests() && ok;
        ok = runS2CItemSubcontainerPacketSelfTests() && ok;
        ok = runS2CMyRoomPacketSelfTests() && ok;
        ok = runS2CMyRoomOperationPacketSelfTests() && ok;
        ok = runS2CPacketControlPacketSelfTests() && ok;
        ok = runS2CPBXResultPacketSelfTests() && ok;
        ok = runS2CPartyReqPacketSelfTests() && ok;
        ok = runS2CPendingNumPacketSelfTests() && ok;
        ok = runS2CPendingStrPacketSelfTests() && ok;
        ok = runS2CPetSyncPacketSelfTests() && ok;
        ok = runS2CFAQGMParamPacketSelfTests() && ok;
        ok = runS2CFishPacketSelfTests() && ok;
        ok = runS2CFriendPassPacketSelfTests() && ok;
        ok = runS2CRecipePacketSelfTests() && ok;
        ok = runS2CRegistrationPacketSelfTests() && ok;
        ok = runS2CResPacketSelfTests() && ok;
        ok = runS2CROEActiveLogPacketSelfTests() && ok;
        ok = runS2CROELogPacketSelfTests() && ok;
        ok = runS2CScenarioItemPacketSelfTests() && ok;
        ok = runS2CUnityPacketSelfTests() && ok;
        ok = runS2CGMPacketSelfTests() && ok;
        ok = runS2CGMSupportPacketSelfTests() && ok;
        ok = runS2CGrapListPacketSelfTests() && ok;
        ok = runS2CGroupAttrPacketSelfTests() && ok;
        ok = runS2CGroupCheckIDPacketSelfTests() && ok;
        ok = runS2CGroupComlinkPacketSelfTests() && ok;
        ok = runS2CGroupEffectsPacketSelfTests() && ok;
        ok = runS2CGroupSolicitReqPacketSelfTests() && ok;
        ok = runS2CGuildListPacketSelfTests() && ok;
        ok = runS2CGuildResultPacketSelfTests() && ok;
        ok = runS2CInspectMessagePacketSelfTests() && ok;
        ok = runS2CLinkshellMessagePacketSelfTests() && ok;
        ok = runS2CMessagePacketSelfTests() && ok;
        ok = runS2CSchedulorPacketSelfTests() && ok;
        ok = runS2CSystemMesPacketSelfTests() && ok;
        ok = runS2CTalkNumPacketSelfTests() && ok;
        ok = runS2CTalkNumWorkPacketSelfTests() && ok;
        ok = runS2CTalkNumWork2PacketSelfTests() && ok;
        ok = runS2CTalkNumNamePacketSelfTests() && ok;
        ok = runS2CTrophyListPacketSelfTests() && ok;
        ok = runS2CTrophySolutionPacketSelfTests() && ok;
        ok = runS2CTrackingListPacketSelfTests() && ok;
        ok = runS2CTrackingStatePacketSelfTests() && ok;
        ok = runS2CTrackingPosPacketSelfTests() && ok;
        ok = runS2CTranslatePacketSelfTests() && ok;
        ok = runS2CWPosPacketSelfTests() && ok;

        return ok;
    }
}

int main(int argc, char** argv)
{
    TracySetThreadName("Test Thread");

    auto testApp = std::make_unique<TestApplication>(argc, argv);

    charutils::SetCharacterPersistenceSuppressedForTests(true);
    const auto omegaSelfTestsSuccess = runOmegaSelfTests();
    charutils::SetCharacterPersistenceSuppressedForTests(false);

    const auto success = testApp->run();

    const auto exitCode = success && omegaSelfTestsSuccess ? EXIT_SUCCESS : EXIT_FAILURE;

    // Explicitly destroy TestApplication before the lua state get cleaned up
    testApp.reset();

    // TODO: This should be in ~Application but it needs more testing for xi_map
    // TODO: This wouldn't be needed if lua wasn't global
    lua_cleanup();

#ifdef TRACY_ENABLE
    // TODO: Tracy profiler exits when program is done
    // Is there an option to keep it running despite the program exiting?
    std::cout << "Press Enter to exit..." << std::endl;
    std::cin.get();
#endif

    return exitCode;
}
