local aern = require('scripts/mixins/families/aern')

describe('Aern mixin pets', function()
    it('plans elemental and call-pet spawns plus BST/SMN-only respawns', function()
        assert(xi.mix.aern.petSpawnPlan(xi.job.SMN, true, 0) == nil)
        local elemental = xi.mix.aern.petSpawnPlan(xi.job.SMN, false, 5)
        assert(elemental.castElemental and elemental.elementalCount == 6)
        assert(xi.mix.aern.petSpawnPlan(xi.job.SMN, false, 6) == nil)
        local bst = xi.mix.aern.petSpawnPlan(xi.job.BST, false, 0)
        assert(bst.callPet and bst.inactiveTime == 3000 and bst.ignoreBusy)
        assert(xi.mix.aern.petSpawnPlan(xi.job.DRG, false, 0).callPet)
        assert(xi.mix.aern.petSpawnPlan(xi.job.WAR, false, 0) == nil)
        assert(xi.mix.aern.shouldRespawnPet(100, 100, false, xi.job.BST))
        assert(xi.mix.aern.shouldRespawnPet(100, 100, false, xi.job.SMN))
        assert(not xi.mix.aern.shouldRespawnPet(100, 100, false, xi.job.DRG))
        assert(not xi.mix.aern.shouldRespawnPet(100, 100, true, xi.job.BST))
        assert(not xi.mix.aern.shouldRespawnPet(99, 100, false, xi.job.BST))
    end)
end)
