local aern = require('scripts/mixins/families/aern')

describe('Aern mixin bracelets', function()
    it('uses strict timers, fixed toggle deltas, and inclusive damage activation', function()
        local on = xi.mix.aern.braceletPlan(0, 100)
        assert(on.active == 1 and on.timer == 130 and on.animationSub == 2 and on.attp == 30 and on.delayp == -33 and on.acc == 40)
        local off = xi.mix.aern.braceletPlan(1, 100)
        assert(off.active == 0 and off.timer == 180 and off.damageTaken == 0 and off.animationSub == 1 and off.attp == -30 and off.delayp == 33 and off.acc == -40)
        assert(xi.mix.aern.braceletPlan(2, 100) == nil)
        assert(not xi.mix.aern.shouldToggleTimer(100, 100) and xi.mix.aern.shouldToggleTimer(101, 100))
        assert(xi.mix.aern.damagePlan(1, 299, 1) == nil)
        local damage = xi.mix.aern.damagePlan(0, 250, 50)
        assert(damage.damageTaken == 300 and damage.shouldToggle)
        assert(not xi.mix.aern.reraisePlan(0, 0, 60, 0).reraise)
        assert(not xi.mix.aern.reraisePlan(1, 1, 100, 0).reraise)
        local reraise = xi.mix.aern.reraisePlan(1, 0, 61, 0)
        assert(reraise.reraise and reraise.noDrops == 1)
    end)
end)
