local atori = require('scripts/mixins/families/atori_tutori_qm')

describe('Atori-Tutori mixin', function()
    it('latches first engagement and uses strict HPP special admission', function()
        assert(xi.mix.atoriTutori.spawnThreshold() == 35)
        assert(xi.mix.atoriTutori.engagePlan(9, 123) == nil)
        assert(xi.mix.atoriTutori.engagePlan(0, 123).engaged == 123)
        assert(xi.mix.atoriTutori.specialPlan(35, 35) == nil)
        local special = xi.mix.atoriTutori.specialPlan(34, 35)
        assert(special.threshold == 0 and special.power == 1 and special.duration == 30)
        assert(xi.mix.atoriTutori.isTerror(xi.effect.TERROR))
        assert(not xi.mix.atoriTutori.isTerror(xi.effect.SILENCE))
    end)
end)
