require('scripts/globals/automaton')

describe('Automaton add burden value', function()
    it('uses flat costs for dark maneuvers by frame', function()
        assert(xi.automaton.addBurdenValue(true, true, 0) == 8)
        assert(xi.automaton.addBurdenValue(true, false, 0) == 14)
    end)

    it('uses the elemental stat-delta ladder', function()
        assert(xi.automaton.addBurdenValue(false, false, 4) == 14)
        assert(xi.automaton.addBurdenValue(false, false, 0) == 19)
        assert(xi.automaton.addBurdenValue(false, false, 3) == 16)
        assert(xi.automaton.addBurdenValue(false, false, -1) == 20)
    end)
end)

describe('Automaton maneuver count pure half', function()
    it('caps at three and fills under Overdrive', function()
        assert(xi.automaton.maneuverCount(2, false) == 2)
        assert(xi.automaton.maneuverCount(5, false) == 3)
        assert(xi.automaton.maneuverCount(1, true) == 3)
        assert(xi.automaton.maneuverCount(0, true) == 0)
    end)
end)

describe('Automaton repair kit regen value', function()
    it('returns zero without data and sums base plus HP percent', function()
        assert(xi.automaton.repairKitRegenValue(false, 1, 0.2, 1000) == 0)
        assert(xi.automaton.repairKitRegenValue(true, 2, 0.4, 1000) == 6)
    end)
end)

describe('Automaton mana tank refresh value', function()
    it('returns zero without data and sums base plus MP percent', function()
        assert(xi.automaton.manaTankRefreshValue(false, 1, 0.2, 500) == 0)
        assert(xi.automaton.manaTankRefreshValue(true, 3, 0.6, 500) == 6)
    end)
end)

describe('Automaton optic fiber name gate', function()
    it('matches optic_fiber substring', function()
        assert(xi.automaton.isOpticFiber('optic_fiber'))
        assert(xi.automaton.isOpticFiber('optic_fiber_ii'))
        assert(not xi.automaton.isOpticFiber('mana_tank'))
    end)
end)

describe('Automaton performance boost sum', function()
    it('sums injected Optic Fiber values', function()
        assert(xi.automaton.performanceBoostSum({ 5, 10, 3 }) == 18)
        assert(xi.automaton.performanceBoostSum({}) == 0)
    end)
end)

describe('Automaton maneuver effect power', function()
    it('is 1 + level/15 + MANEUVER_BONUS', function()
        assert(xi.automaton.maneuverEffectPower(75, 0) == 6)
        assert(xi.automaton.maneuverEffectPower(30, 2) == 5)
    end)
end)

describe('Automaton maneuver duration clamp', function()
    it('clamps to [60, 300]', function()
        assert(xi.automaton.clampManeuverDuration(30) == 60)
        assert(xi.automaton.clampManeuverDuration(400) == 300)
        assert(xi.automaton.clampManeuverDuration(120) == 120)
    end)
end)

describe('Automaton overload prevented', function()
    it('requires overload, prevent mod, and water delete', function()
        assert(xi.automaton.overloadPrevented(true, true, true))
        assert(not xi.automaton.overloadPrevented(false, true, true))
        assert(not xi.automaton.overloadPrevented(true, false, true))
        assert(not xi.automaton.overloadPrevented(true, true, false))
    end)
end)

describe('Automaton should remove oldest maneuver', function()
    it('is true only at three active', function()
        assert(xi.automaton.shouldRemoveOldestManeuver(3))
        assert(not xi.automaton.shouldRemoveOldestManeuver(2))
    end)
end)
