local colibri = require('scripts/mixins/families/colibri_mimic')

describe('Colibri Mimic mixin', function()
    it('accepts, casts, expires, and resets copied spells at strict time boundaries', function()
        local accept = xi.mix.colibriMimic.acceptPlan(false, true, true, false, false, 123, 100)
        assert(accept.spell == 123 and accept.castWindow == 130 and accept.castTime == 106 and accept.animationSub == 5)
        assert(xi.mix.colibriMimic.acceptPlan(true, true, true, false, false, 123, 100) == nil)
        assert(xi.mix.colibriMimic.acceptPlan(false, true, true, true, false, 123, 100) == nil)
        assert(xi.mix.colibriMimic.acceptPlan(false, true, true, true, true, 123, 100) ~= nil)

        assert(xi.mix.colibriMimic.combatPlan(5, 123, 130, 106, 106, false) == nil)
        local cast = xi.mix.colibriMimic.combatPlan(5, 123, 130, 106, 107, false)
        assert(cast.castSpell == 123 and cast.animationSub == 4 and cast.spell == 0)
        assert(xi.mix.colibriMimic.combatPlan(5, 123, 130, 106, 130, false) == nil)
        local expired = xi.mix.colibriMimic.combatPlan(5, 123, 130, 106, 131, false)
        assert(expired.animationSub == 4 and expired.spell == 0)
        assert(xi.mix.colibriMimic.combatPlan(5, 123, 130, 106, 107, true) == nil)
        assert(xi.mix.colibriMimic.combatPlan(4, 123, 130, 106, 107, false) == nil)
    end)
end)
