describe('Base entity MP helper bindings', function()
    ---@type CClientEntityPair
    local player

    before_each(function()
        player = xi.test.world:spawnPlayer({
            zone = xi.zone.WEST_RONFAURE,
        })
    end)

    it('reads and updates battle entity MP while NPCs fall back', function()
        local npc = player.entities:get('Field_Manual')
        local mob = player.entities:moveTo('Wild_Rabbit')

        assert(npc, 'Field Manual NPC was not found')
        assert(mob, 'Wild Rabbit mob was not found')
        mob:spawn()

        mob:setMaxMP(1000)
        assert(mob:getMaxMP() == 1000, 'setMaxMP did not update mob max MP')
        assert(mob:getBaseMP() == 1000, 'getBaseMP did not report raw mob max MP')

        mob:setMP(333)
        assert(mob:getMP() == 333, 'setMP did not update mob MP')
        assert(mob:getMPP() == 33, 'getMPP should floor the mob MP percent')

        assert(mob:addMP(200) == 200, 'addMP did not report restored mob MP')
        assert(mob:getMP() == 533, 'addMP did not restore mob MP')

        assert(mob:addMP(9999) == 467, 'addMP did not report capped restore')
        assert(mob:getMP() == 1000, 'addMP did not cap mob MP')
        assert(mob:getMPP() == 100, 'capped mob MP should be 100 percent')

        mob:setMP(700)
        assert(mob:restoreMP(500) == 300, 'restoreMP did not report capped restore')
        assert(mob:getMP() == 1000, 'restoreMP did not cap at max MP')

        assert(mob:delMP(275) == 275, 'delMP did not report spent mob MP')
        assert(mob:getMP() == 725, 'delMP did not subtract mob MP')

        mob:setMP(25)
        assert(mob:delMP(999) == 25, 'delMP did not report capped MP loss')
        assert(mob:getMP() == 0, 'delMP did not floor mob MP')
        assert(mob:getMPP() == 0, 'zero MP should report zero MPP')
        assert(mob:restoreMP(40) == 40, 'restoreMP did not restore from zero MP')
        assert(mob:getMP() == 40, 'restoreMP did not update zero MP')
        assert(mob:getMPP() == 4, 'low nonzero MPP should floor to 4 percent')

        mob:setMP(500)
        mob:setMaxMP(300)
        assert(mob:getMaxMP() == 300, 'setMaxMP did not lower mob max MP')
        assert(mob:getMP() == 300, 'setMaxMP did not clamp current MP')
        mob:setMaxMP(0)
        assert(mob:getMaxMP() == 0, 'setMaxMP should floor max MP at zero')
        assert(mob:getMP() == 0, 'setMaxMP zero floor should clamp current MP to zero')
        assert(mob:getMPP() == 0, 'zero max/current MP should report zero MPP')

        player:setMaxMP(20000)
        assert(player:getBaseMP() == 20000, 'player getBaseMP should keep raw max MP')
        assert(player:getMaxMP() == 9999, 'player getMaxMP should clamp effective max MP')
        player:setMP(20000)
        assert(player:getMP() == 9999, 'player setMP should cap at effective max MP')
        player:setMP(9990)
        assert(player:addMP(50) == 9, 'player addMP should report effective max MP cap')
        assert(player:getMP() == 9999, 'player addMP should cap at effective max MP')

        mob:setMaxMP(30000000)
        mob:setMP(30000000)
        assert(mob:getMPP() == 100, 'large mob MP should not overflow MPP calculation')

        mob:setMaxMP(1000)
        mob:setMP(500)
        mob:setAnimation(xi.animation.DEATH)
        assert(mob:restoreMP(50) == 0, 'restoreMP should not restore during death animation')
        assert(mob:getMP() == 500, 'restoreMP during death animation should not change MP')
        mob:setAnimation(xi.animation.NONE)

        assert(npc:getMP() == 0, 'NPC getMP should fall back to zero')
        assert(npc:getMPP() == 0, 'NPC getMPP should fall back to zero')
        assert(npc:getMaxMP() == 0, 'NPC getMaxMP should fall back to zero')
        assert(npc:getBaseMP() == 0, 'NPC getBaseMP should fall back to zero')
        assert(npc:addMP(100) == 0, 'NPC addMP should fall back to zero')
        assert(npc:restoreMP(100) == 0, 'NPC restoreMP should fall back to zero')
        assert(npc:delMP(100) == 0, 'NPC delMP should fall back to zero')
        assert(pcall(npc.setMP, npc, 100), 'NPC setMP rejected a valid no-op')
        assert(pcall(npc.setMaxMP, npc, 100), 'NPC setMaxMP rejected a valid no-op')
        assert(npc:getMP() == 0, 'NPC MP should remain zero after no-op mutators')

        assert(not pcall(mob.getMP), 'getMP accepted missing self')
        assert(not pcall(mob.getMPP), 'getMPP accepted missing self')
        assert(not pcall(mob.getMaxMP), 'getMaxMP accepted missing self')
        assert(not pcall(mob.getBaseMP), 'getBaseMP accepted missing self')
        assert(not pcall(mob.setMP), 'setMP accepted missing self')
        assert(not pcall(mob.setMP, mob), 'setMP accepted missing MP')
        assert(not pcall(mob.setMP, mob, 'bad'), 'setMP accepted non-numeric MP')
        assert(not pcall(mob.setMaxMP), 'setMaxMP accepted missing self')
        assert(not pcall(mob.setMaxMP, mob), 'setMaxMP accepted missing MP')
        assert(not pcall(mob.setMaxMP, mob, 'bad'), 'setMaxMP accepted non-numeric MP')
        assert(not pcall(mob.addMP), 'addMP accepted missing self')
        assert(not pcall(mob.addMP, mob), 'addMP accepted missing MP')
        assert(not pcall(mob.addMP, mob, 'bad'), 'addMP accepted non-numeric MP')
        assert(not pcall(mob.restoreMP), 'restoreMP accepted missing self')
        assert(not pcall(mob.restoreMP, mob), 'restoreMP accepted missing MP')
        assert(not pcall(mob.restoreMP, mob, 'bad'), 'restoreMP accepted non-numeric MP')
        assert(not pcall(mob.delMP), 'delMP accepted missing self')
        assert(not pcall(mob.delMP, mob), 'delMP accepted missing MP')
        assert(not pcall(mob.delMP, mob, 'bad'), 'delMP accepted non-numeric MP')
    end)
end)
