describe('Base entity health update helper bindings', function()
    ---@type CClientEntityPair
    local player

    before_each(function()
        player = xi.test.world:spawnPlayer({
            zone = xi.zone.WEST_RONFAURE,
        })
    end)

    it('recalculates effective HP and MP from raw maxima and modifiers', function()
        local mob = player.entities:moveTo('Wild_Rabbit')

        assert(mob, 'Wild Rabbit mob was not found')
        mob:spawn()
        mob:setMaxHP(1000)
        mob:setMaxMP(500)
        mob:setHP(1000)
        mob:setMP(500)

        mob:addMod(xi.mod.BASE_HP, 100)
        mob:addMod(xi.mod.BASE_MP, 50)
        mob:addMod(xi.mod.HPP, 10)
        mob:addMod(xi.mod.MPP, 20)
        mob:addMod(xi.mod.FOOD_HP, 30)
        mob:addMod(xi.mod.FOOD_MP, 15)
        mob:addMod(xi.mod.FOOD_HPP, 10)
        mob:addMod(xi.mod.FOOD_HP_CAP, 50)
        mob:addMod(xi.mod.FOOD_MPP, 20)
        mob:addMod(xi.mod.FOOD_MP_CAP, 75)
        mob:updateHealth()

        assert(mob:getBaseHP() == 1000, 'getBaseHP should retain the raw maximum')
        assert(mob:getMaxHP() == 1293, 'getMaxHP should include HP modifiers and food cap')
        assert(mob:getHP() == 1000, 'health update should preserve current HP below the new cap')
        assert(mob:getHPP() == 77, 'getHPP should use the recalculated effective HP')
        assert(mob:getBaseMP() == 500, 'getBaseMP should retain the raw maximum')
        assert(mob:getMaxMP() == 753, 'getMaxMP should include MP modifiers and food cap')
        assert(mob:getMP() == 500, 'health update should preserve current MP below the new cap')
        assert(mob:getMPP() == 66, 'getMPP should use the recalculated effective MP')

        mob:delMod(xi.mod.BASE_HP, 100)
        mob:delMod(xi.mod.BASE_MP, 50)
        mob:delMod(xi.mod.HPP, 10)
        mob:delMod(xi.mod.MPP, 20)
        mob:delMod(xi.mod.FOOD_HP, 30)
        mob:delMod(xi.mod.FOOD_MP, 15)
        mob:delMod(xi.mod.FOOD_HPP, 10)
        mob:delMod(xi.mod.FOOD_HP_CAP, 50)
        mob:delMod(xi.mod.FOOD_MPP, 20)
        mob:delMod(xi.mod.FOOD_MP_CAP, 75)

        mob:setMaxHP(100)
        mob:setMaxMP(50)
        mob:setHP(100)
        mob:setMP(50)
        mob:addMod(xi.mod.CONVMPTOHP, 20)
        mob:updateHealth()
        assert(mob:getMaxHP() == 120, 'MP-to-HP conversion should increase max HP')
        assert(mob:getMaxMP() == 30, 'MP-to-HP conversion should decrease max MP')

        mob:delMod(xi.mod.CONVMPTOHP, 20)
        mob:addMod(xi.mod.CONVHPTOMP, 20)
        mob:updateHealth()
        assert(mob:getMaxHP() == 80, 'HP-to-MP conversion should decrease max HP')
        assert(mob:getMaxMP() == 70, 'HP-to-MP conversion should increase max MP')

        mob:delMod(xi.mod.CONVHPTOMP, 20)
        mob:setMaxHP(7000)
        mob:setHP(7000)
        mob:addMod(xi.mod.FOOD_HPP, 1000)
        mob:addMod(xi.mod.FOOD_HP_CAP, 30000)
        mob:updateHealth()
        assert(mob:getMaxHP() == 11464, 'food bonus should follow LSB int16 narrowing')

        mob:delMod(xi.mod.FOOD_HPP, 1000)
        mob:delMod(xi.mod.FOOD_HP_CAP, 30000)
        mob:setMaxHP(16777217)
        mob:setHP(16777217)
        mob:updateHealth()
        assert(mob:getBaseHP() == 16777217, 'large raw max HP should remain exact')
        assert(mob:getMaxHP() == 16777216, 'large effective HP should follow LSB float rounding')
        assert(mob:getHP() == 16777216, 'large current HP should clamp to rounded effective max')

        mob:setMaxHP(100)
        mob:setHP(100)
        mob:addMod(xi.mod.WEAKNESS_PCT, -100)
        mob:updateHealth()
        assert(mob:getMaxHP() == 0, 'fully weakened mob should have zero effective max HP')
        assert(mob:getHP() == 0, 'fully weakened mob should clamp current HP to zero')
        assert(mob:getHPP() == 0, 'zero effective HP should report zero HPP')
        mob:delMod(xi.mod.WEAKNESS_PCT, -100)

        player:setMaxHP(20000)
        player:setHP(20000)
        player:addMod(xi.mod.BASE_HP, 1000)
        player:updateHealth()
        assert(player:getBaseHP() == 20000, 'player base HP should remain raw after updateHealth')
        assert(player:getMaxHP() == 9999, 'player effective HP should retain the 9999 cap')
        assert(player:getHP() == 9999, 'player current HP should clamp to the effective cap')

        mob:despawn()
    end)
end)
