local gear = require('scripts/mixins/families/gear')

describe('Gear mixin', function()
    it('uses inclusive triple-to-double and double-to-single HPP boundaries', function()
        assert(xi.mix.gear.stageForHPP(61, 60, 30) == 0)
        assert(xi.mix.gear.stageForHPP(60, 60, 30) == 1)
        assert(xi.mix.gear.stageForHPP(30, 60, 30) == 1)
        assert(xi.mix.gear.stageForHPP(29, 60, 30) == 2)
        assert(xi.mix.gear.skillListForStage(0) == 150 and xi.mix.gear.skillListForStage(1) == 151 and xi.mix.gear.skillListForStage(2) == 152)
        assert(xi.mix.gear.skillListForStage(nil) == nil)
        assert(xi.mix.gear.shouldChangeStage(0, 1))
        assert(not xi.mix.gear.shouldChangeStage(1, 1))
        assert(not xi.mix.gear.shouldChangeStage(0, nil))
        assert(xi.mix.gear.shouldDropDefense(1, 0))
        assert(xi.mix.gear.shouldDropDefense(2, 0))
        assert(not xi.mix.gear.shouldDropDefense(0, 0))
        assert(not xi.mix.gear.shouldDropDefense(1, 1))
    end)
end)
