local ghrah = require('scripts/mixins/families/ghrah')

describe('Ghrah mixin', function()
    it('plans each form and alternates only after a strict timer', function()
        local ball = xi.mix.ghrah.formPlan(0, 10, 20, 30, 75)
        assert(ball.baseDamageModifier == 0 and ball.att == 10 and ball.def == 20 and ball.eva == 30 and ball.tripleAttack == 0 and not ball.aggressive)
        local human = xi.mix.ghrah.formPlan(1, 10, 20, 30, 75)
        assert(human.def == 100 and human.aggressive and human.animationSub == 1)
        local spider = xi.mix.ghrah.formPlan(2, 10, 20, 30, 75)
        assert(spider.baseDamageModifier == 77 and spider.att == 21 and spider.def == 31 and spider.eva == 30)
        local bird = xi.mix.ghrah.formPlan(3, 10, 20, 30, 75)
        assert(bird.eva == 78 and bird.tripleAttack == 5)
        assert(xi.mix.ghrah.formChangePlan(100, 100, 0, 2) == nil)
        local emerge = xi.mix.ghrah.formChangePlan(101, 100, 0, 2)
        assert(emerge.form == 2 and emerge.changeTime == 161)
        local retract = xi.mix.ghrah.formChangePlan(101, 100, 2, 3)
        assert(retract.form == 0 and retract.changeTime == 161)
    end)
end)
