local gigas = require('scripts/mixins/families/gigas_bst_nm')
describe('Gigas Beastmaster NM', function()
 it('uses inclusive HPP and ready timestamps, Familiar for live pets', function()
  assert(xi.mix.gigasBeastmaster.engagePlan(10,2).engageReadyTime==12)
  assert(xi.mix.gigasBeastmaster.abilityPlan(11,12,0,40,40,true,7200)==nil)
  assert(xi.mix.gigasBeastmaster.abilityPlan(12,12,0,41,40,true,7200)==nil)
  local p=xi.mix.gigasBeastmaster.abilityPlan(12,12,0,40,40,true,7200)
  assert(p.ability==xi.mobSkill.FAMILIAR_1 and p.nextReadyTime==7212)
  assert(xi.mix.gigasBeastmaster.abilityPlan(12,12,0,40,40,false,7200).ability==xi.mobSkill.CHARM)
 end)
end)
