local hpemde = require('scripts/mixins/families/hpemde')

describe('Hpemde mixin', function()
    it('plans dive, activation, mouth transitions, and damage close', function()
        local dive = xi.mix.hpemde.divePlan(true)
        assert(not dive.autoAttack and not dive.mobAbility and dive.hideName and dive.untargetable and dive.animationSub == 5)
        local noDive = xi.mix.hpemde.divePlan(false)
        assert(not noDive.autoAttack and not noDive.mobAbility and noDive.animationSub == nil)
        local surface = xi.mix.hpemde.surfacePlan(5)
        assert(not surface.hideName and not surface.untargetable and surface.animationSub == 6 and surface.waitMs == 2000)
        local open = xi.mix.hpemde.openMouthPlan(75)
        assert(open.baseDamageModifier == 77 and open.damageMod == 10000 and open.animationSub == 3 and open.waitMs == 2000)
        local close = xi.mix.hpemde.closeMouthPlan(100)
        assert(close.baseDamageModifier == 0 and close.damageMod == 0 and close.changeTime == 130 and close.animationSub == 6)

        local active = xi.mix.hpemde.combatPlan(0, 99, 100, 145, 100, 6, 0, 50)
        assert(active.action == 'activate' and active.changeTime == 130)
        local timeout = xi.mix.hpemde.combatPlan(0, 100, 100, 100, 101, 6, 0, 50)
        assert(timeout.action == 'disengage')
        assert(xi.mix.hpemde.combatPlan(1, 100, 100, 0, 100, 6, 100, 50) == nil)
        assert(xi.mix.hpemde.combatPlan(1, 100, 100, 0, 101, 6, 100, 50).action == 'open')
        assert(xi.mix.hpemde.combatPlan(1, 49, 100, 0, 100, 3, 0, 50).action == 'close')
        assert(xi.mix.hpemde.shouldCloseMouth(3, 250))
        assert(not xi.mix.hpemde.shouldCloseMouth(3, 249))
    end)
end)
