require('scripts/globals/mobskills')

describe('Mob physical skill TP floor', function()
    it('floors skill TP at 1000', function()
        assert(xi.mobskills.mobPhysicalSkillTP(500) == 1000)
        assert(xi.mobskills.mobPhysicalSkillTP(1000) == 1000)
        assert(xi.mobskills.mobPhysicalSkillTP(2500) == 2500)
    end)
end)

describe('Mob physical base damage', function()
    it('floors the product and floors at one', function()
        assert(xi.mobskills.mobPhysicalBaseDamage(10, 2, 3, 1.5) == 22)
        assert(xi.mobskills.mobPhysicalBaseDamage(0, 0, 0, 1) == 1)
        assert(xi.mobskills.mobPhysicalBaseDamage(0, 0, 0, 0) == 1)
    end)
end)

describe('Mob physical subsequent damage', function()
    it('reuses first-hit base when no subsequent fTP table', function()
        assert(xi.mobskills.mobPhysicalSubsequentDamage(10, 2, 3, 2, false, 22) == 22)
    end)

    it('floors without the max(1) floor when a table is present', function()
        assert(xi.mobskills.mobPhysicalSubsequentDamage(10, 2, 3, 2, true, 22) == 30)
        assert(xi.mobskills.mobPhysicalSubsequentDamage(0, 0, 0, 0, true, 1) == 0)
    end)
end)

describe('Special attack evasion bonus', function()
    it('negates the target mod', function()
        assert(xi.mobskills.specialAttackEvasionBonus(15) == -15)
        assert(xi.mobskills.specialAttackEvasionBonus(0) == 0)
    end)
end)

describe('Mighty Strikes crit plan', function()
    it('forces full crit chance when active', function()
        local can, table = xi.mobskills.mightyStrikesCritPlan(false)
        assert(not can)

        can, table = xi.mobskills.mightyStrikesCritPlan(true)
        assert(can)
        assert(table[1] == 1 and table[2] == 1 and table[3] == 1)
    end)
end)

describe('Breath damage cap default', function()
    it('is floor of current HP over five', function()
        assert(xi.mobskills.breathDamageCapDefault(1000) == 200)
        assert(xi.mobskills.breathDamageCapDefault(999) == 199)
    end)
end)

describe('Optional TP factor', function()
    it('uses the default when no table is present', function()
        assert(xi.mobskills.optionalTPFactor(false, 1.5, 1) == 1)
        assert(xi.mobskills.optionalTPFactor(true, 1.5, 1) == 1.5)
    end)
end)

describe('Ignore defense plan', function()
    it('enables only when a table is present', function()
        local factor, enabled = xi.mobskills.ignoreDefensePlan(false, 0.5)
        assert(factor == 0 and not enabled)

        factor, enabled = xi.mobskills.ignoreDefensePlan(true, 0.5)
        assert(factor == 0.5 and enabled)
    end)
end)
