require('scripts/globals/mobskills')

describe('Mob drain move plan', function()
    it('damages undead without healing, ignoring drain type', function()
        local plan = xi.mobskills.planDrainMove(true, xi.mobskills.drainType.MP, 100, 40)
        assert(plan.amount == 40)
        assert(plan.message == xi.msg.basic.DAMAGE)
        assert(plan.damagesTarget)
        assert(not plan.healsMob)
        assert(plan.applies)
    end)

    it('clamps living HP/MP/TP drains and selects messages', function()
        local hp = xi.mobskills.planDrainMove(false, xi.mobskills.drainType.HP, 100, 30)
        assert(hp.amount == 30 and hp.message == xi.msg.basic.SKILL_DRAIN_HP)
        assert(hp.damagesTarget and hp.healsMob)

        local mp = xi.mobskills.planDrainMove(false, xi.mobskills.drainType.MP, 50, 80)
        assert(mp.amount == 50 and mp.message == xi.msg.basic.SKILL_DRAIN_MP)
        assert(not mp.damagesTarget and mp.healsMob)

        local tp = xi.mobskills.planDrainMove(false, xi.mobskills.drainType.TP, 200, 150)
        assert(tp.amount == 150 and tp.message == xi.msg.basic.SKILL_DRAIN_TP)
    end)

    it('returns no effect for unknown living drain types', function()
        local plan = xi.mobskills.planDrainMove(false, 99, 10, 10)
        assert(not plan.applies)
        assert(plan.message == xi.msg.basic.SKILL_NO_EFFECT)
        assert(plan.amount == 0)
    end)
end)

describe('Mob heal amount', function()
    it('clamps to missing HP', function()
        assert(xi.mobskills.mobHealAmount(100, 900, 1000) == 100)
        assert(xi.mobskills.mobHealAmount(200, 900, 1000) == 100)
        assert(xi.mobskills.mobHealAmount(50, 1000, 1000) == 0)
    end)
end)

describe('Mob status effect move plan', function()
    it('returns no effect when the target cannot gain the effect', function()
        local plan = xi.mobskills.planStatusEffectMove(false, false, false, false, 60, 1)
        assert(plan.message == xi.msg.basic.SKILL_NO_EFFECT)
        assert(not plan.applyEffect)
    end)

    it('misses on immunity, resist trait, or nullify', function()
        assert(xi.mobskills.planStatusEffectMove(true, true, false, false, 60, 1).message == xi.msg.basic.SKILL_MISS)
        assert(xi.mobskills.planStatusEffectMove(true, false, true, false, 60, 1).message == xi.msg.basic.SKILL_MISS)
        assert(xi.mobskills.planStatusEffectMove(true, false, false, true, 60, 1).message == xi.msg.basic.SKILL_MISS)
    end)

    it('applies when resist rate is at least 0.25 and floors duration', function()
        local miss = xi.mobskills.planStatusEffectMove(true, false, false, false, 60, 0.24)
        assert(miss.message == xi.msg.basic.SKILL_MISS and not miss.applyEffect)

        local plan = xi.mobskills.planStatusEffectMove(true, false, false, false, 60, 0.25)
        assert(plan.applyEffect and plan.message == xi.msg.basic.SKILL_ENFEEB_IS)
        assert(plan.totalDuration == 15)

        plan = xi.mobskills.planStatusEffectMove(true, false, false, false, 100, 0.5)
        assert(plan.totalDuration == 50)
    end)
end)

describe('Mob gaze applies', function()
    it('requires both facing conditions', function()
        assert(xi.mobskills.gazeApplies(true, true))
        assert(not xi.mobskills.gazeApplies(true, false))
        assert(not xi.mobskills.gazeApplies(false, true))
    end)
end)

describe('Mob buff move message', function()
    it('maps addStatusEffect success', function()
        assert(xi.mobskills.buffMoveMessage(true) == xi.msg.basic.SKILL_GAIN_EFFECT)
        assert(xi.mobskills.buffMoveMessage(false) == xi.msg.basic.SKILL_NO_EFFECT)
    end)
end)

describe('Mob drain attribute correlation', function()
    it('maps STR_DOWN through CHR_DOWN to the matching boost', function()
        assert(xi.mobskills.drainAttributeBoost(xi.effect.STR_DOWN) == xi.effect.STR_BOOST)
        assert(xi.mobskills.drainAttributeBoost(xi.effect.CHR_DOWN) == xi.effect.CHR_BOOST)
        assert(xi.mobskills.drainAttributeBoost(xi.effect.STR_DOWN - 1) == nil)
        assert(xi.mobskills.drainAttributeBoost(xi.effect.CHR_DOWN + 1) == nil)
    end)

    it('plans attribute drain messages from the enfeeble result', function()
        local boost, msg, apply = xi.mobskills.drainAttributePlan(xi.effect.STR_DOWN, xi.msg.basic.SKILL_ENFEEB_IS)
        assert(boost == xi.effect.STR_BOOST and msg == xi.msg.basic.ATTR_DRAINED and apply)

        boost, msg, apply = xi.mobskills.drainAttributePlan(xi.effect.STR_DOWN, xi.msg.basic.SKILL_MISS)
        assert(boost == xi.effect.STR_BOOST and msg == xi.msg.basic.SKILL_MISS and not apply)

        boost, msg, apply = xi.mobskills.drainAttributePlan(1, xi.msg.basic.SKILL_ENFEEB_IS)
        assert(boost == nil and msg == xi.msg.basic.SKILL_NO_EFFECT and not apply)
    end)
end)

describe('Mob drain status effect message', function()
    it('prefers hysteria none, then steal, then no effect', function()
        assert(xi.mobskills.drainStatusEffectMessage(true, true) == xi.msg.basic.NONE)
        assert(xi.mobskills.drainStatusEffectMessage(false, true) == xi.msg.basic.EFFECT_DRAINED)
        assert(xi.mobskills.drainStatusEffectMessage(false, false) == xi.msg.basic.SKILL_NO_EFFECT)
    end)
end)
