require('scripts/globals/mobskills')

describe('Mob skill resolve pDIF', function()
    it('returns one when skipPDIF is set', function()
        assert(xi.mobskills.resolvePDIF(true, 2.5) == 1)
        assert(xi.mobskills.resolvePDIF(false, 2.5) == 2.5)
    end)
end)

describe('Mob skill block reduction input', function()
    it('floors base times pDIF', function()
        assert(xi.mobskills.blockReductionInput(10, 1.5) == 15)
        assert(xi.mobskills.blockReductionInput(10, 1.15) == 11)
        assert(xi.mobskills.blockReductionInput(0, 2) == 0)
    end)
end)

describe('Mob skill block-on-hit plan', function()
    it('requires a block that is not skipped', function()
        local plan = xi.mobskills.planBlockOnHit(false, false, 10)
        assert(not plan.hitBlocked and not plan.blockedWithShieldMastery)

        plan = xi.mobskills.planBlockOnHit(true, true, 10)
        assert(not plan.hitBlocked)

        plan = xi.mobskills.planBlockOnHit(true, false, 0)
        assert(plan.hitBlocked and not plan.blockedWithShieldMastery)

        plan = xi.mobskills.planBlockOnHit(true, false, 5)
        assert(plan.hitBlocked and plan.blockedWithShieldMastery)
    end)
end)

describe('Mob skill post-hit damage plan', function()
    it('gates skill-up and interrupt on positive damage', function()
        local plan = xi.mobskills.planPostHitDamage(0, false)
        assert(not plan.tryEvasionSkillUp and not plan.tryHitInterrupt)

        plan = xi.mobskills.planPostHitDamage(10, false)
        assert(plan.tryEvasionSkillUp and plan.tryHitInterrupt)

        plan = xi.mobskills.planPostHitDamage(10, true)
        assert(plan.tryEvasionSkillUp and not plan.tryHitInterrupt)
    end)
end)

describe('Mob skill successful hit info', function()
    it('fills landed bookkeeping on a default hit', function()
        local hit = xi.mobskills.successfulHitInfo(3, 42, true, true, 1.75)
        assert(hit.hitNumber == 3)
        assert(hit.hitLanded)
        assert(hit.hitDamage == 42)
        assert(hit.hitBlocked)
        assert(hit.isCritical)
        assert(hit.pDif == 1.75)
        assert(not hit.hitParried and not hit.hitGuarded)
    end)
end)

describe('Mob skill crit rate applies', function()
    it('mirrors canCrit truthiness', function()
        assert(xi.mobskills.critRateApplies(true))
        assert(not xi.mobskills.critRateApplies(false))
        assert(not xi.mobskills.critRateApplies(nil))
    end)
end)
