require('scripts/globals/pets')

describe('Pet mob-skill admission', function()
    it('blocks summoning when no pet is assigned or a pet is already spawned', function()
        assert(xi.pet.mobSkillCheckResult(false, false) == 1)
        assert(xi.pet.mobSkillCheckResult(true, true) == 1)
    end)

    it('allows summoning for an assigned but unspawned pet', function()
        assert(xi.pet.mobSkillCheckResult(true, false) == 0)
    end)
end)

describe('Pet casting admission', function()
    it('applies existing-pet, Astral Flow, and area gates in order', function()
        assert(xi.pet.castingCheckResult(true, true, false, false, true, 40, false) == 315)
        assert(xi.pet.castingCheckResult(false, true, false, true, true, 40, false) == 581)
        assert(xi.pet.castingCheckResult(false, false, false, false, true, 40, false) == 316)
    end)

    it('uses the PC mini-fight result and non-PC assigned-pet gate', function()
        assert(xi.pet.castingCheckResult(false, false, false, true, true, 40, false) == 40)
        assert(xi.pet.castingCheckResult(false, false, false, true, true, 0, false) == 0)
        assert(xi.pet.castingCheckResult(false, false, false, true, false, 0, false) == 1)
        assert(xi.pet.castingCheckResult(false, false, false, true, false, 0, true) == 0)
    end)
end)
