require('scripts/globals/pets')

describe('Beastmaster master-death pet cleanup', function()
    it('despawns only a living, unengaged assigned pet', function()
        assert(not xi.pet.shouldDespawnOnMasterDeath(false, true, false))
        assert(not xi.pet.shouldDespawnOnMasterDeath(true, false, false))
        assert(not xi.pet.shouldDespawnOnMasterDeath(true, true, true))
        assert(xi.pet.shouldDespawnOnMasterDeath(true, true, false))
    end)
end)

describe('Non-PC pet spawn state', function()
    it('suppresses the state message for non-PC casters only', function()
        assert(not xi.pet.spawnPetStatePlan(true, true, true).suppressStateMessage)
        assert(not xi.pet.spawnPetStatePlan(false, false, true).suppressStateMessage)
        assert(xi.pet.spawnPetStatePlan(false, true, false).suppressStateMessage)
    end)

    it('adds Beastmaster cleanup listeners only for Call Beast', function()
        local callBeast = xi.pet.spawnPetStatePlan(false, true, true)
        assert(callBeast.addMasterDeathListener and callBeast.addMasterDespawnListener)

        local other = xi.pet.spawnPetStatePlan(false, true, false)
        assert(not other.addMasterDeathListener and not other.addMasterDespawnListener)
    end)
end)

describe('Avatar pet spawn effects', function()
    it('reapplies Favor and selects the special-avatar actions', function()
        local alexander = xi.pet.avatarSpawnPlan(true, true, xi.petId.ALEXANDER, false, true)
        assert(alexander.resetFavor and alexander.applyFavorAura and alexander.applyFavorDebuffs)
        assert(alexander.timers[1].delay == 5000 and alexander.timers[1].ability == xi.jobAbility.PERFECT_DEFENSE and alexander.timers[1].target == 'pet')

        local odin = xi.pet.avatarSpawnPlan(true, false, xi.petId.ODIN, true, false)
        assert(odin.attackTarget and #odin.timers == 0)

        local atomos = xi.pet.avatarSpawnPlan(true, false, xi.petId.ATOMOS, true, true)
        assert(#atomos.timers == 2)
        assert(atomos.timers[1].delay == 3000 and atomos.timers[1].ability == xi.jobAbility.DECONSTRUCTION and atomos.timers[1].target == 'target')
        assert(atomos.timers[2].delay == 10000 and atomos.timers[2].ability == xi.jobAbility.CHRONOSHIFT and atomos.timers[2].target == 'pet')
    end)

    it('does nothing for non-avatars or unavailable special-action inputs', function()
        local nonAvatar = xi.pet.avatarSpawnPlan(false, true, xi.petId.ALEXANDER, true, true)
        assert(not nonAvatar.resetFavor and not nonAvatar.attackTarget and #nonAvatar.timers == 0)

        local noPet = xi.pet.avatarSpawnPlan(true, false, xi.petId.ALEXANDER, false, false)
        assert(#noPet.timers == 0)
    end)
end)

describe('Pet mob-skill admission', function()
    it('blocks summoning when no pet is assigned or a pet is already spawned', function()
        assert(xi.pet.mobSkillCheckResult(false, false) == 1)
        assert(xi.pet.mobSkillCheckResult(true, true) == 1)
    end)

    it('allows summoning for an assigned but unspawned pet', function()
        assert(xi.pet.mobSkillCheckResult(true, false) == 0)
    end)
end)

describe('Pet casting admission', function()
    it('applies existing-pet, Astral Flow, and area gates in order', function()
        assert(xi.pet.castingCheckResult(true, true, false, false, true, 40, false) == 315)
        assert(xi.pet.castingCheckResult(false, true, false, true, true, 40, false) == 581)
        assert(xi.pet.castingCheckResult(false, false, false, false, true, 40, false) == 316)
    end)

    it('uses the PC mini-fight result and non-PC assigned-pet gate', function()
        assert(xi.pet.castingCheckResult(false, false, false, true, true, 40, false) == 40)
        assert(xi.pet.castingCheckResult(false, false, false, true, true, 0, false) == 0)
        assert(xi.pet.castingCheckResult(false, false, false, true, false, 0, false) == 1)
        assert(xi.pet.castingCheckResult(false, false, false, true, false, 0, true) == 0)
    end)
end)

describe('Pet Familiar buffs', function()
    it('requires a present, living, not-yet-buffed pet and owner', function()
        assert(not xi.pet.familiarBuffsShouldApply(false, true, true, false))
        assert(not xi.pet.familiarBuffsShouldApply(true, false, true, false))
        assert(not xi.pet.familiarBuffsShouldApply(true, true, false, false))
        assert(not xi.pet.familiarBuffsShouldApply(true, true, true, true))
        assert(xi.pet.familiarBuffsShouldApply(true, true, true, false))
    end)

    it('plans charm duration, haste, and the ten-percent HP boost', function()
        local full = xi.pet.familiarBuffPlan(5, true, 101)
        assert(full.extendCharm)
        assert(full.charmMinSeconds == 1800 and full.charmMaxSeconds == 2100)
        assert(full.hasteAbility == 500)
        assert(math.abs(full.addedHP - 10.1) < 0.000001)

        local noBonus = xi.pet.familiarBuffPlan(0, false, 100)
        assert(not noBonus.extendCharm)
        assert(noBonus.charmMinSeconds == nil and noBonus.charmMaxSeconds == nil)
        assert(noBonus.hasteAbility == 0 and noBonus.addedHP == 10)
    end)
end)

describe('Mob pet assignment', function()
    it('requires a mob, matching pet, and unassigned pair', function()
        assert(not xi.pet.setMobPetPlan(false, true, true, true, false, false, true, true).linkPet)
        assert(not xi.pet.setMobPetPlan(true, false, true, true, false, false, true, true).linkPet)
        assert(not xi.pet.setMobPetPlan(true, true, false, true, false, false, true, true).linkPet)
        assert(not xi.pet.setMobPetPlan(true, true, true, false, false, false, true, true).linkPet)
        assert(not xi.pet.setMobPetPlan(true, true, true, true, true, false, true, true).linkPet)
        assert(not xi.pet.setMobPetPlan(true, true, true, true, false, true, true, true).linkPet)
    end)

    it('always disallows respawn and only despawns an unspawned master pair', function()
        local active = xi.pet.setMobPetPlan(true, true, true, true, false, false, true, true)
        assert(active.disallowRespawn and active.linkPet and not active.despawnPet)

        local dormant = xi.pet.setMobPetPlan(true, true, true, true, false, false, false, true)
        assert(dormant.disallowRespawn and dormant.linkPet and dormant.despawnPet)
    end)
end)
