require('scripts/globals/pets')

describe('Pet mob-skill admission', function()
    it('blocks summoning when no pet is assigned or a pet is already spawned', function()
        assert(xi.pet.mobSkillCheckResult(false, false) == 1)
        assert(xi.pet.mobSkillCheckResult(true, true) == 1)
    end)

    it('allows summoning for an assigned but unspawned pet', function()
        assert(xi.pet.mobSkillCheckResult(true, false) == 0)
    end)
end)

describe('Pet casting admission', function()
    it('applies existing-pet, Astral Flow, and area gates in order', function()
        assert(xi.pet.castingCheckResult(true, true, false, false, true, 40, false) == 315)
        assert(xi.pet.castingCheckResult(false, true, false, true, true, 40, false) == 581)
        assert(xi.pet.castingCheckResult(false, false, false, false, true, 40, false) == 316)
    end)

    it('uses the PC mini-fight result and non-PC assigned-pet gate', function()
        assert(xi.pet.castingCheckResult(false, false, false, true, true, 40, false) == 40)
        assert(xi.pet.castingCheckResult(false, false, false, true, true, 0, false) == 0)
        assert(xi.pet.castingCheckResult(false, false, false, true, false, 0, false) == 1)
        assert(xi.pet.castingCheckResult(false, false, false, true, false, 0, true) == 0)
    end)
end)

describe('Pet Familiar buffs', function()
    it('requires a present, living, not-yet-buffed pet and owner', function()
        assert(not xi.pet.familiarBuffsShouldApply(false, true, true, false))
        assert(not xi.pet.familiarBuffsShouldApply(true, false, true, false))
        assert(not xi.pet.familiarBuffsShouldApply(true, true, false, false))
        assert(not xi.pet.familiarBuffsShouldApply(true, true, true, true))
        assert(xi.pet.familiarBuffsShouldApply(true, true, true, false))
    end)

    it('plans charm duration, haste, and the ten-percent HP boost', function()
        local full = xi.pet.familiarBuffPlan(5, true, 101)
        assert(full.extendCharm)
        assert(full.charmMinSeconds == 1800 and full.charmMaxSeconds == 2100)
        assert(full.hasteAbility == 500)
        assert(math.abs(full.addedHP - 10.1) < 0.000001)

        local noBonus = xi.pet.familiarBuffPlan(0, false, 100)
        assert(not noBonus.extendCharm)
        assert(noBonus.charmMinSeconds == nil and noBonus.charmMaxSeconds == nil)
        assert(noBonus.hasteAbility == 0 and noBonus.addedHP == 10)
    end)
end)

describe('Mob pet assignment', function()
    it('requires a mob, matching pet, and unassigned pair', function()
        assert(not xi.pet.setMobPetPlan(false, true, true, true, false, false, true, true).linkPet)
        assert(not xi.pet.setMobPetPlan(true, false, true, true, false, false, true, true).linkPet)
        assert(not xi.pet.setMobPetPlan(true, true, false, true, false, false, true, true).linkPet)
        assert(not xi.pet.setMobPetPlan(true, true, true, false, false, false, true, true).linkPet)
        assert(not xi.pet.setMobPetPlan(true, true, true, true, true, false, true, true).linkPet)
        assert(not xi.pet.setMobPetPlan(true, true, true, true, false, true, true, true).linkPet)
    end)

    it('always disallows respawn and only despawns an unspawned master pair', function()
        local active = xi.pet.setMobPetPlan(true, true, true, true, false, false, true, true)
        assert(active.disallowRespawn and active.linkPet and not active.despawnPet)

        local dormant = xi.pet.setMobPetPlan(true, true, true, true, false, false, false, true)
        assert(dormant.disallowRespawn and dormant.linkPet and dormant.despawnPet)
    end)
end)
