local rampart = require('scripts/mixins/families/rampart')
describe('Rampart timed Reinforcements', function()
 it('uses availability/limit disable, strict due, and source scheduling', function()
  assert(xi.mix.rampart.shouldDisableTimedSpawn(false,0,0))
  assert(xi.mix.rampart.shouldDisableTimedSpawn(true,2,2))
  assert(not xi.mix.rampart.shouldDisableTimedSpawn(true,2,0))
  assert(xi.mix.rampart.nextPetTime(100,3)==160)
  assert(xi.mix.rampart.nextPetAfterSpawn(60,160,0)==220)
  assert(xi.mix.rampart.nextPetAfterSpawn(1,160,3)==220)
  assert(not xi.mix.rampart.isPetDue(160,160) and xi.mix.rampart.isPetDue(161,160))
 end)
end)
