local rampart = require('scripts/mixins/families/rampart')
describe('Rampart mixin', function()
    it('plans door transitions with strict combat timing', function()
        local engage = xi.mix.rampart.engagePlan(0)
        assert(engage.stun and engage.animationSub == 1 and engage.swapTime == 30)
        assert(not xi.mix.rampart.engagePlan(1).stun)
        assert(xi.mix.rampart.roamPlan(false, 0, 1).animationSub == 0)
        assert(xi.mix.rampart.roamPlan(false, 1, 0).animationSub == 1)
        assert(xi.mix.rampart.roamPlan(true, 0, 1) == nil)
        assert(xi.mix.rampart.combatPlan(30, 30, false, 0) == nil)
        assert(xi.mix.rampart.combatPlan(31, 30, true, 0) == nil)
        assert(xi.mix.rampart.combatPlan(31, 30, false, 0).swapTime == 61)
        assert(xi.mix.rampart.combatPlan(31, 30, false, 1).swapTime == 40)
    end)
end)
