require('scripts/globals/weaponskills')

describe('Magic weaponskill attack slot', function()
    it('uses ranged for archery/marksmanship', function()
        assert(xi.weaponskills.magicWSAttackSlot(xi.skill.ARCHERY) == xi.slot.RANGED)
        assert(xi.weaponskills.magicWSAttackSlot(xi.skill.MARKSMANSHIP) == xi.slot.RANGED)
        assert(xi.weaponskills.magicWSAttackSlot(xi.skill.STAFF) == xi.slot.MAIN)
        assert(xi.weaponskills.magicWSAttackSlot(0) == xi.slot.MAIN)
    end)
end)

describe('Magic weaponskill bonus accuracy', function()
    it('adds WSACC onto gearAccFromFTP', function()
        assert(xi.weaponskills.magicWSBonusAcc(40, 10) == 50)
        assert(xi.weaponskills.magicWSBonusAcc(0, 0) == 0)
    end)
end)

describe('Magic weaponskill scarlet product', function()
    it('multiplies without flooring', function()
        assert(xi.weaponskills.magicWSScarletProduct(100, 1.5) == 150)
        assert(xi.weaponskills.magicWSScarletProduct(100, 1) == 100)
    end)
end)

describe('Magic weaponskill negative early return', function()
    it('is true only for strictly negative damage', function()
        assert(xi.weaponskills.magicWSNegativeEarlyReturn(-1))
        assert(not xi.weaponskills.magicWSNegativeEarlyReturn(0))
        assert(not xi.weaponskills.magicWSNegativeEarlyReturn(1))
    end)
end)

describe('Magic weaponskill shadow absorb plan', function()
    it('sets one shadow and zero damage', function()
        local plan = xi.weaponskills.planMagicWSShadowAbsorb()
        assert(plan.shadowsAbsorbed == 1)
        assert(plan.damage == 0)
        assert(not plan.trySkillUp)
    end)
end)

describe('Magic weaponskill skill-up gate', function()
    it('requires positive damage', function()
        assert(xi.weaponskills.magicWSSkillUpApplies(1))
        assert(not xi.weaponskills.magicWSSkillUpApplies(0))
        assert(not xi.weaponskills.magicWSSkillUpApplies(-5))
    end)
end)

describe('Weaponskill floor raw final damage', function()
    it('floors toward -inf like math.floor', function()
        assert(xi.weaponskills.floorRawFinalDmg(99.9) == 99)
        assert(xi.weaponskills.floorRawFinalDmg(100) == 100)
    end)
end)

describe('Weaponskill hybrid magic add', function()
    it('sums physical final and hybrid magic component', function()
        assert(xi.weaponskills.hybridMagicAdd(100, 25) == 125)
    end)
end)

describe('Weaponskill should remove ammo', function()
    it('is true when any ammo was used', function()
        assert(xi.weaponskills.shouldRemoveAmmo(1))
        assert(xi.weaponskills.shouldRemoveAmmo(3))
        assert(not xi.weaponskills.shouldRemoveAmmo(0))
    end)
end)

describe('Magic weaponskill hit counter pins', function()
    it('uses one landed TP hit', function()
        assert(xi.weaponskills.magicWSHitsLanded == 1)
        assert(xi.weaponskills.magicWSTpHitsLanded == 1)
        assert(xi.weaponskills.magicWSExtraHitsLanded == 0)
    end)
end)
