require('scripts/globals/weaponskills')

describe('Weaponskill ranged ammo inventory count', function()
    it('returns -1 when not tracking', function()
        assert(xi.weaponskills.rangedAmmoInventoryCount(false, true, true, 5) == -1)
        assert(xi.weaponskills.rangedAmmoInventoryCount(true, false, true, 5) == -1)
    end)

    it('returns zero without an ammo item and quantity when present', function()
        assert(xi.weaponskills.rangedAmmoInventoryCount(true, true, false, 5) == 0)
        assert(xi.weaponskills.rangedAmmoInventoryCount(true, true, true, 12) == 12)
    end)

    it('tracks zero and positive counts', function()
        assert(not xi.weaponskills.ammoTrackingActive(-1))
        assert(xi.weaponskills.ammoTrackingActive(0))
        assert(xi.weaponskills.ammoTrackingActive(3))
    end)
end)

describe('Weaponskill first-hit landed plan', function()
    it('requires skill type and positive damage', function()
        assert(not xi.weaponskills.planFirstHitLanded(false, 100, true).applies)
        assert(not xi.weaponskills.planFirstHitLanded(true, 0, true).applies)
    end)

    it('forces mainHitsLanded to zero and tpHitsLanded to one', function()
        local plan = xi.weaponskills.planFirstHitLanded(true, 50, false)
        assert(plan.applies and plan.trySkillUp and not plan.addJumpTP)
        assert(plan.tpHitsLanded == 1 and plan.mainHitsLanded == 0)

        plan = xi.weaponskills.planFirstHitLanded(true, 50, true)
        assert(plan.addJumpTP and plan.mainHitsLanded == 0)
    end)
end)

describe('Weaponskill subsequent-hit landed plan', function()
    it('classifies main multi-hits and offhand second swings', function()
        local plan = xi.weaponskills.planSubsequentHitLanded(0, true, false, false, 2, false, false)
        assert(not plan.applies)

        plan = xi.weaponskills.planSubsequentHitLanded(10, true, false, false, 2, false, false)
        assert(plan.applies and plan.addJumpTP and plan.tpClass == 'main')

        plan = xi.weaponskills.planSubsequentHitLanded(10, false, false, true, 1, false, true)
        assert(plan.tpClass == 'tp')
    end)
end)

describe('Weaponskill apply hit TP class', function()
    it('increments the matching counter', function()
        local tp, main, off = xi.weaponskills.applyHitTPClass('tp', 1, 0, 0)
        assert(tp == 2 and main == 0 and off == 0)
        tp, main, off = xi.weaponskills.applyHitTPClass('main', 1, 2, 0)
        assert(tp == 1 and main == 3 and off == 0)
        tp, main, off = xi.weaponskills.applyHitTPClass('offhand', 1, 2, 3)
        assert(tp == 1 and main == 2 and off == 4)
    end)
end)

describe('Weaponskill H2H offhand plan', function()
    it('swaps offhand skill and sub TP for H2H', function()
        local plan = xi.weaponskills.planH2HOffhand(xi.skill.DAGGER, 2)
        assert(not plan.isH2H and plan.offhandSkill == 2)

        plan = xi.weaponskills.planH2HOffhand(xi.skill.HAND_TO_HAND, 2)
        assert(plan.isH2H and plan.subTPUsesMainhand)
        assert(plan.offhandSkill == xi.skill.HAND_TO_HAND)
    end)
end)

describe('Weaponskill extra hits landed', function()
    it('sums main and offhand multi counters', function()
        assert(xi.weaponskills.extraHitsLanded(3, 2) == 5)
        assert(xi.weaponskills.extraHitsLanded(0, 0) == 0)
    end)
end)

describe('Weaponskill ammo step plan', function()
    it('stops when ammo is exhausted', function()
        local plan = xi.weaponskills.planAmmoStep(false, 0, 5, 1)
        assert(plan.ammoUsed == 0 and not plan.forceStop)

        plan = xi.weaponskills.planAmmoStep(true, 0, 2, 1)
        assert(plan.ammoUsed == 1 and not plan.forceStop)

        plan = xi.weaponskills.planAmmoStep(true, 1, 2, 1)
        assert(plan.ammoUsed == 2 and plan.forceStop)
    end)
end)

describe('Weaponskill jump TP gain', function()
    it('multiplies mainhand TP return by attacker mult', function()
        assert(xi.weaponskills.jumpTPGain(100, 1.5) == 150)
    end)
end)
