require('scripts/globals/weaponskills')

describe('Weaponskill single-hit miss gate', function()
    it('misses when the roll exceeds hit rate', function()
        assert(xi.weaponskills.singleHitMisses(0.8, 0.5, false, false))
        assert(not xi.weaponskills.singleHitMisses(0.5, 0.5, false, false))
        assert(not xi.weaponskills.singleHitMisses(0.4, 0.5, false, false))
    end)

    it('never misses on a guaranteed hit unless mustMiss', function()
        assert(not xi.weaponskills.singleHitMisses(0.99, 0.1, true, false))
        assert(xi.weaponskills.singleHitMisses(0.0, 1.0, true, true))
        assert(xi.weaponskills.singleHitMisses(0.0, 1.0, false, true))
    end)
end)

describe('Weaponskill single-hit parry and shadow eligibility', function()
    it('allows parry only for non-guaranteed physical hits', function()
        assert(xi.weaponskills.singleHitMayParry(true, false))
        assert(not xi.weaponskills.singleHitMayParry(true, true))
        assert(not xi.weaponskills.singleHitMayParry(false, false))
    end)

    it('allows shadow absorb only when not guaranteed and not ignoreShadows', function()
        assert(xi.weaponskills.singleHitMayShadowAbsorb(false, false))
        assert(not xi.weaponskills.singleHitMayShadowAbsorb(true, false))
        assert(not xi.weaponskills.singleHitMayShadowAbsorb(false, true))
        assert(not xi.weaponskills.singleHitMayShadowAbsorb(true, true))
    end)
end)

describe('Weaponskill single-hit critical', function()
    it('crits from the varies roll, forced first, or Mighty Strikes', function()
        assert(xi.weaponskills.singleHitIsCritical(true, 0.1, 0.2, false, false))
        assert(not xi.weaponskills.singleHitIsCritical(true, 0.3, 0.2, false, false))
        assert(not xi.weaponskills.singleHitIsCritical(false, 0.0, 1.0, false, false))
        assert(xi.weaponskills.singleHitIsCritical(false, 0.9, 0.1, true, false))
        assert(xi.weaponskills.singleHitIsCritical(false, 0.9, 0.1, false, true))
    end)
end)

describe('Weaponskill single-hit damage', function()
    it('multiplies dmg plus consume mana by fTP and pDIF', function()
        -- (100 + 10) * 1.5 * 2 = 330
        assert(xi.weaponskills.singleHitDamage(100, 10, 1.5, 2, false, 0) == 330)
    end)

    it('subtracts block reduction without flooring', function()
        -- 100 * 1 * 1 = 100, -25 = 75
        assert(xi.weaponskills.singleHitDamage(100, 0, 1, 1, true, 25) == 75)
    end)
end)

describe('Weaponskill guarded pDIF', function()
    it('drops pDIF by one with a zero floor', function()
        assert(xi.weaponskills.guardedPDIF(2.5) == 1.5)
        assert(xi.weaponskills.guardedPDIF(0.5) == 0)
        assert(xi.weaponskills.guardedPDIF(1.0) == 0)
    end)
end)
