require('scripts/globals/weaponskills')

describe('Weaponskill bonus fTP or zero', function()
    it('defaults absent bonusfTP to zero', function()
        assert(xi.weaponskills.bonusFTPOrZero(false, 1.5) == 0)
        assert(xi.weaponskills.bonusFTPOrZero(true, 1.5) == 1.5)
        assert(xi.weaponskills.bonusFTPOrZero(true, 0) == 0)
    end)
end)

describe('Weaponskill hybrid magic positive gate', function()
    it('is true only for strictly positive damage', function()
        assert(xi.weaponskills.hybridMagicPositive(1))
        assert(not xi.weaponskills.hybridMagicPositive(0))
        assert(not xi.weaponskills.hybridMagicPositive(-1))
    end)
end)

describe('Weaponskill hybrid magic post-severe', function()
    it('skips absorb when non-positive', function()
        assert(xi.weaponskills.hybridMagicPostSevere(0, -1, 1) == 0)
        assert(xi.weaponskills.hybridMagicPostSevere(-5, -1, 1) == -5)
    end)

    it('applies floored absorb/nullify when positive', function()
        assert(xi.weaponskills.hybridMagicPostSevere(100, 0.5, 1) == 50)
        assert(xi.weaponskills.hybridMagicPostSevere(100, 1, 0) == 0)
    end)
end)

describe('Weaponskill hybrid magic should mitigate', function()
    it('matches the positive gate', function()
        assert(xi.weaponskills.hybridMagicShouldMitigate(1))
        assert(not xi.weaponskills.hybridMagicShouldMitigate(0))
    end)
end)

describe('Weaponskill floor hybrid magic final', function()
    it('floors toward -inf', function()
        assert(xi.weaponskills.floorHybridMagicFinal(99.9) == 99)
        assert(xi.weaponskills.floorHybridMagicFinal(100) == 100)
        assert(xi.weaponskills.floorHybridMagicFinal(-1.5) == -2)
    end)
end)
