require('scripts/globals/weaponskills')

describe('Weaponskill default mult or', function()
    it('defaults to one when absent', function()
        assert(xi.weaponskills.defaultMultOr(false, 2) == 1)
        assert(xi.weaponskills.defaultMultOr(true, 1.5) == 1.5)
    end)
end)

describe('Weaponskill should record damage', function()
    it('requires any TP or extra hit', function()
        assert(xi.weaponskills.shouldRecordWSDamage(1, 0))
        assert(xi.weaponskills.shouldRecordWSDamage(0, 1))
        assert(not xi.weaponskills.shouldRecordWSDamage(0, 0))
    end)
end)

describe('Weaponskill enmity helpers', function()
    it('selects TA and multiplies damage', function()
        assert(xi.weaponskills.enmityEntityUsesTA(true))
        assert(not xi.weaponskills.enmityEntityUsesTA(false))
        assert(xi.weaponskills.enmityFromDamageAmount(100, 1.5) == 150)
        assert(xi.weaponskills.enmityFromDamageAmount(-50, 2) == -100)
    end)
end)

describe('Weaponskill Sengikori plan', function()
    it('requires hits and an active effect', function()
        assert(not xi.weaponskills.planSengikori(0, 0, true, 10, 5, false).applies)
        assert(not xi.weaponskills.planSengikori(1, 0, false, 10, 5, false).applies)
    end)

    it('adds bonus power and picks MB vs SC debuff', function()
        local plan = xi.weaponskills.planSengikori(1, 0, true, 10, 5, false)
        assert(plan.applies and plan.power == 15 and not plan.applyMBDebuff and plan.delSengikori)

        plan = xi.weaponskills.planSengikori(0, 2, true, 20, 0, true)
        assert(plan.applies and plan.power == 20 and plan.applyMBDebuff)
    end)

    it('applies even when damage is zero if hits landed', function()
        assert(xi.weaponskills.planSengikori(1, 0, true, 1, 0, false).applies)
    end)
end)

describe('Weaponskill hit local var', function()
    it('packs WS id in the top eight bits', function()
        assert(xi.weaponskills.weaponskillHitLocalVar(1, 100) == bit.lshift(1, 24) + 100)
        assert(xi.weaponskills.weaponskillHitLocalVar(255, 1) == bit.lshift(255, 24) + 1)
    end)

    it('only sets when damage is positive', function()
        assert(xi.weaponskills.shouldSetWeaponskillHitVar(1))
        assert(not xi.weaponskills.shouldSetWeaponskillHitVar(0))
        assert(not xi.weaponskills.shouldSetWeaponskillHitVar(-1))
    end)
end)

describe('Weaponskill TP hits for core', function()
    it('multiplies landed TP hits by attacker TP mult', function()
        assert(xi.weaponskills.tpHitsForCore(2, 1.5) == 3)
        assert(xi.weaponskills.tpHitsForCore(0, 2) == 0)
    end)
end)

describe('Weaponskill abs final damage', function()
    it('matches math.abs', function()
        assert(xi.weaponskills.absFinalDamage(-42) == 42)
        assert(xi.weaponskills.absFinalDamage(42) == 42)
        assert(xi.weaponskills.absFinalDamage(0) == 0)
    end)
end)
