require('scripts/globals/weaponskills')

describe('Weaponskill gear acc from fTP', function()
    it('ceils gear fTP times one hundred', function()
        assert(xi.weaponskills.gearAccFromFTP(0) == 0)
        assert(xi.weaponskills.gearAccFromFTP(1.0) == 100)
        assert(xi.weaponskills.gearAccFromFTP(0.125) == 13) -- ceil(12.5)
        assert(xi.weaponskills.gearAccFromFTP(0.101) == 11) -- ceil(10.1)
    end)
end)

describe('Weaponskill physical must-miss', function()
    it('misses on Perfect Dodge', function()
        assert(xi.weaponskills.physicalMustMiss(true, false, false))
        assert(xi.weaponskills.physicalMustMiss(true, true, true))
    end)

    it('misses on ALL_MISS unless hitsHigh', function()
        assert(xi.weaponskills.physicalMustMiss(false, true, false))
        assert(not xi.weaponskills.physicalMustMiss(false, true, true))
        assert(not xi.weaponskills.physicalMustMiss(false, false, false))
    end)
end)

describe('Weaponskill SA/TA applicability gates', function()
    it('requires SA and (behind or Hide or Doubt)', function()
        assert(xi.weaponskills.sneakApplicable(true, true, false, false))
        assert(xi.weaponskills.sneakApplicable(true, false, true, false))
        assert(xi.weaponskills.sneakApplicable(true, false, false, true))
        assert(not xi.weaponskills.sneakApplicable(true, false, false, false))
        assert(not xi.weaponskills.sneakApplicable(false, true, true, true))
    end)

    it('derives TA, Assassin, guaranteed hit, and forced first crit', function()
        assert(xi.weaponskills.trickApplicable(true))
        assert(not xi.weaponskills.trickApplicable(false))
        assert(xi.weaponskills.assassinApplicable(true, true))
        assert(not xi.weaponskills.assassinApplicable(true, false))
        assert(not xi.weaponskills.assassinApplicable(false, true))
        assert(xi.weaponskills.guaranteedHit(true, false))
        assert(xi.weaponskills.guaranteedHit(false, true))
        assert(not xi.weaponskills.guaranteedHit(false, false))
        assert(xi.weaponskills.forcedFirstCrit(true, false))
        assert(xi.weaponskills.forcedFirstCrit(false, true))
        assert(not xi.weaponskills.forcedFirstCrit(false, false))
    end)
end)

describe('Weaponskill physical bonus injects', function()
    it('zeros fTP and WSmods on Jump and uses jump acc', function()
        local fTP, acc, wsm = xi.weaponskills.physicalBonusInjects(true, 0.5, 50, 30, 10, 7)
        assert(fTP == 0 and acc == 30 and wsm == 0)
    end)

    it('uses gear fTP and gearAcc plus WSACC when not Jump', function()
        local fTP, acc, wsm = xi.weaponskills.physicalBonusInjects(false, 0.5, 50, 30, 10, 7)
        assert(fTP == 0.5 and acc == 60 and wsm == 7)
        fTP, acc, wsm = xi.weaponskills.physicalBonusInjects(false, 0.5, 50, 30, 10, nil)
        assert(wsm == 0)
    end)

    it('adds accVaries fTP onto bonus acc', function()
        assert(xi.weaponskills.bonusAccWithVaries(50, 12.5) == 62.5)
    end)
end)

describe('Weaponskill hybrid and power helpers', function()
    it('applies hybrid magic only when hybrid and target HP remains', function()
        assert(xi.weaponskills.hybridMagicApplies(true, 100, 50))
        assert(not xi.weaponskills.hybridMagicApplies(true, 50, 50))
        assert(not xi.weaponskills.hybridMagicApplies(true, 40, 50))
        assert(not xi.weaponskills.hybridMagicApplies(false, 100, 50))
    end)

    it('multiplies by server weaponskill power', function()
        assert(xi.weaponskills.applyWeaponSkillPower(100, 1.0) == 100)
        assert(xi.weaponskills.applyWeaponSkillPower(100, 1.5) == 150)
    end)

    it('floors ranged mitigation after pierce SDT scale', function()
        -- 100 * (1 + 2500/10000) = 125
        assert(xi.weaponskills.rangedWeaponskillMitigation(100, 2500) == 125)
        -- floor(101 * 1.1) = floor(111.1) = 111
        assert(xi.weaponskills.rangedWeaponskillMitigation(101, 1000) == 111)
    end)
end)
