require('scripts/globals/weaponskills')

describe('Weaponskill take-damage message plan', function()
    it('uses DAMAGE and HIT when primary hits deal positive damage', function()
        local p = xi.weaponskills.takeWeaponskillDamagePlan(1, 100, 0, true, 0)
        assert(p.message == xi.msg.basic.DAMAGE)
        assert(p.setResolution and p.resolution == xi.action.resolution.HIT)
        assert(not p.setParam)
    end)

    it('uses DAMAGE_SECONDARY for non-primary positive damage', function()
        local p = xi.weaponskills.takeWeaponskillDamagePlan(1, 50, 0, false, 0)
        assert(p.message == xi.msg.basic.DAMAGE_SECONDARY)
        assert(p.setResolution and p.resolution == xi.action.resolution.HIT)
    end)

    it('uses GUARD resolution when any hit was guarded', function()
        local p = xi.weaponskills.takeWeaponskillDamagePlan(2, 10, 0, true, 1)
        assert(p.setResolution and p.resolution == xi.action.resolution.GUARD)
    end)

    -- Hits landed with zero damage still set the damage message but no resolution.
    it('sets damage message without resolution when damage is zero', function()
        local p = xi.weaponskills.takeWeaponskillDamagePlan(1, 0, 0, true, 0)
        assert(p.message == xi.msg.basic.DAMAGE)
        assert(not p.setResolution)
    end)

    it('uses self-heal messages for negative damage', function()
        local p = xi.weaponskills.takeWeaponskillDamagePlan(1, -20, 0, true, 0)
        assert(p.message == xi.msg.basic.SELF_HEAL)
        assert(not p.setResolution)
        p = xi.weaponskills.takeWeaponskillDamagePlan(1, -20, 0, false, 0)
        assert(p.message == xi.msg.basic.SELF_HEAL_SECONDARY)
    end)

    it('uses SHADOW_ABSORB with param when no hits but shadows absorbed', function()
        local p = xi.weaponskills.takeWeaponskillDamagePlan(0, 0, 3, true, 0)
        assert(p.message == xi.msg.basic.SHADOW_ABSORB)
        assert(p.setParam and p.param == 3)
        assert(p.setResolution and p.resolution == xi.action.resolution.MISS)
    end)

    it('uses SKILL_MISS or EVADES on a total miss', function()
        local p = xi.weaponskills.takeWeaponskillDamagePlan(0, 0, 0, true, 0)
        assert(p.message == xi.msg.basic.SKILL_MISS)
        assert(p.setResolution and p.resolution == xi.action.resolution.MISS)
        p = xi.weaponskills.takeWeaponskillDamagePlan(0, 0, 0, false, 0)
        assert(p.message == xi.msg.basic.EVADES)
    end)
end)

describe('Weaponskill jump and store-TP helpers', function()
    it('zeros attacker TP mult and extra hits on jumps', function()
        local mult, extra = xi.weaponskills.jumpTPAdjust(true, 1.5, 4)
        assert(mult == 0 and extra == 0)
        mult, extra = xi.weaponskills.jumpTPAdjust(false, 1.5, 4)
        assert(mult == 1.5 and extra == 4)
    end)

    it('builds store-TP modifier as one plus mod over one hundred', function()
        assert(xi.weaponskills.storeTPModifier(0) == 1)
        assert(xi.weaponskills.storeTPModifier(25) == 1.25)
        assert(xi.weaponskills.storeTPModifier(-50) == 0.5)
    end)

    it('computes extra-hit TP as ten per hit times store-TP plus bonus', function()
        -- 2 * 10 * 1.25 + 5 = 30
        assert(xi.weaponskills.weaponskillExtraHitTP(2, 1.25, 5) == 30)
        assert(xi.weaponskills.weaponskillExtraHitTP(0, 1.5, 7) == 7)
    end)
end)

describe('Weaponskill enmity override gate', function()
    it('requires both override CE and VE and at least one hit', function()
        assert(xi.weaponskills.weaponskillEnmityUsesOverride(100, 200, 1, 0))
        assert(xi.weaponskills.weaponskillEnmityUsesOverride(0, 0, 0, 1)) -- 0 is set
        assert(not xi.weaponskills.weaponskillEnmityUsesOverride(nil, 200, 1, 0))
        assert(not xi.weaponskills.weaponskillEnmityUsesOverride(100, nil, 1, 0))
        assert(not xi.weaponskills.weaponskillEnmityUsesOverride(100, 200, 0, 0))
    end)
end)
