local zdei = require('scripts/mixins/families/zdei')

describe('Zdei mixin', function()
    it('plans rotation, charge progression, and eligible form changes', function()
        assert(xi.mix.zdei.rotationOffset(xi.mobPool.EOZDEI_LEFT) == -16)
        assert(xi.mix.zdei.rotationOffset(0) == nil)
        local engage = xi.mix.zdei.engagePlan(100, 15)
        assert(engage.animationSub == 1 and engage.changeTime == 115)
        local start = xi.mix.zdei.chargePlan(0, 0, 3)
        assert(start.useCharge and start.chargeCount == 1 and start.chargeTotal == 3 and not start.autoAttack and not start.magicCasting)
        local next = xi.mix.zdei.chargePlan(2, 3, 5)
        assert(next.useCharge and next.chargeCount == 3 and next.chargeTotal == nil)
        assert(xi.mix.zdei.chargePlan(3, 3, 5).useFinal)
        local finish = xi.mix.zdei.finishPlan()
        assert(finish.autoAttack and finish.magicCasting and finish.chargeCount == 0 and finish.chargeTotal == 0)
        assert(xi.mix.zdei.shouldChangeForm(100, 100, true, 0))
        assert(not xi.mix.zdei.shouldChangeForm(100, 101, true, 0))
        assert(not xi.mix.zdei.shouldChangeForm(100, 100, true, 1))
        local form = xi.mix.zdei.formChangePlan(100, 3)
        assert(form.animationSub == 3 and form.changeTime == 160)
    end)
end)
