require('scripts/globals/znm')

describe('ZNM Sanraku rotation plan', function()
    it('retains each newly rolled server value', function()
        local plan = xi.znm.sanrakuRotationPlan(4, 9, 123)
        assert(plan.interest == 4 and plan.fauna == 9 and plan.trades == 123)
    end)
end)

describe('ZNM Sanraku trade rotation', function()
    it('rotates after 500 completed trades', function()
        assert(not xi.znm.shouldRotateSanrakuTrades(499))
        assert(xi.znm.shouldRotateSanrakuTrades(500))
        assert(xi.znm.shouldRotateSanrakuTrades(501))
    end)
end)

describe('ZNM Sanraku trade increment', function()
    it('increments the counter between rotations', function()
        assert(xi.znm.nextSanrakuTradeCount(0) == 1)
        assert(xi.znm.nextSanrakuTradeCount(499) == 500)
    end)
end)

describe('ZNM Sanraku trade plan', function()
    it('rotates at the limit and otherwise increments the counter', function()
        local rotate = xi.znm.serverPlateTradesPlan(500)
        assert(rotate.rotate and rotate.trades == nil)

        local increment = xi.znm.serverPlateTradesPlan(499)
        assert(increment.rotate == nil and increment.trades == 500)
    end)
end)

describe('ZNM Sanraku selection initialization', function()
    it('initializes missing and zero selections only', function()
        assert(xi.znm.shouldInitializeSanrakuSelection(nil))
        assert(xi.znm.shouldInitializeSanrakuSelection(0))
        assert(not xi.znm.shouldInitializeSanrakuSelection(1))
    end)
end)

describe('ZNM Sanraku selection value', function()
    it('uses an initial roll only when the selection is uninitialized', function()
        assert(xi.znm.selectSanrakuSelection(nil, 17) == 17)
        assert(xi.znm.selectSanrakuSelection(0, 17) == 17)
        assert(xi.znm.selectSanrakuSelection(3, 17) == 3)
    end)
end)

describe('ZNM Sanraku daily tracking reset', function()
    it('clears the trade day and plate count', function()
        local plan = xi.znm.dailyTrackingResetPlan()
        assert(plan.tradingDay == 0 and plan.tradedPlates == 0)
    end)
end)
